

import { StyleOption } from './types';

export const HEADSHOT_STYLES: StyleOption[] = [
  // --- PROFESSIONAL (18 Styles) ---
  {
    id: 'corporate-grey',
    name: 'Corporate Studio',
    category: 'Professional',
    description: 'Classic grey backdrop, suit/blazer, perfectly lit studio setting.',
    promptModifier: 'professional corporate headshot, wearing a dark navy business suit, crisp white shirt, against a neutral slate grey studio backdrop, soft studio lighting, confident expression, high quality 8k',
    iconName: 'Briefcase',
    colorFrom: 'from-slate-500',
    colorTo: 'to-slate-700',
    previewUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'pro-tie',
    name: 'Pro with Tie',
    category: 'Professional',
    description: 'Formal business look with a suit and tie.',
    promptModifier: 'professional corporate headshot, wearing a dark navy suit with a silk tie, crisp white shirt, neutral grey studio background, perfectly lit, confident and authoritative, 8k',
    iconName: 'Shirt',
    colorFrom: 'from-blue-700',
    colorTo: 'to-slate-800',
    previewUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'executive-office',
    name: 'Executive Corner',
    category: 'Professional',
    description: 'High-rise view background, authoritative and commanding.',
    promptModifier: 'executive CEO headshot, wearing an expensive tailored suit, background view of a city skyline from a high-rise office window, powerful stance, commanding presence, cinematic lighting, 8k',
    iconName: 'Building2',
    colorFrom: 'from-indigo-600',
    colorTo: 'to-violet-800',
    previewUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'public-leader',
    name: 'Global Leader',
    category: 'Professional',
    description: 'Authoritative, statesman-like pose with dignified background.',
    promptModifier: 'charismatic political leader headshot, wearing a premium dark suit with a flag pin, dignified blurred background of a government building or classic library, authoritative yet approachable, cinematic lighting, 8k',
    iconName: 'Mic2',
    colorFrom: 'from-slate-700',
    colorTo: 'to-blue-900',
    previewUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'legal-counsel',
    name: 'Legal Counsel',
    category: 'Professional',
    description: 'Authoritative, trustworthy look with a classic law library background.',
    promptModifier: 'professional lawyer headshot, wearing a premium dark suit and tie (or professional blazer), background of a classic law library with mahogany bookshelves, authoritative, trustworthy, and confident expression, cinematic lighting, 8k',
    iconName: 'Scale',
    colorFrom: 'from-slate-800',
    colorTo: 'to-gray-900',
    previewUrl: 'https://images.unsplash.com/photo-1558222218-b7b54eede3f3?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'management-consultant',
    name: 'Consultant',
    category: 'Professional',
    description: 'Polished, strategic expert look in a high-end corporate setting.',
    promptModifier: 'strategy consultant headshot, wearing sharp modern business attire, background of a sleek bright corporate boardroom with glass walls, intelligent and approachable expression, professional lighting, 8k',
    iconName: 'LineChart',
    colorFrom: 'from-indigo-600',
    colorTo: 'to-blue-500',
    previewUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'medical-pro',
    name: 'Medical Pro',
    category: 'Professional',
    description: 'Clean white coat, clinical background, trustworthy vibe.',
    promptModifier: 'professional medical headshot, doctor wearing a pristine white lab coat and stethoscope, blurred modern hospital or clinic background, soft bright lighting, trustworthy and knowledgeable expression, 8k',
    iconName: 'Stethoscope',
    colorFrom: 'from-teal-500',
    colorTo: 'to-cyan-600',
    previewUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'real-estate',
    name: 'Real Estate Agent',
    category: 'Professional',
    description: 'Friendly, approachable, luxury home background.',
    promptModifier: 'professional real estate agent headshot, wearing smart business casual blazer, blurred background of a bright luxury modern home interior, airy lighting, friendly welcoming smile, 8k',
    iconName: 'Home',
    colorFrom: 'from-orange-400',
    colorTo: 'to-amber-500',
    previewUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'senior-engineer',
    name: 'Senior Engineer',
    category: 'Professional',
    description: 'Technical professional in a modern industrial setting.',
    promptModifier: 'professional engineer headshot, wearing smart casual workwear (checked shirt or polo), background of a blurred modern architectural site or construction project, analytical and skilled, bright natural light, 8k',
    iconName: 'Ruler',
    colorFrom: 'from-blue-600',
    colorTo: 'to-cyan-700',
    previewUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'modern-tech',
    name: 'Modern Tech',
    category: 'Professional',
    description: 'Smart casual, bright modern office background with bokeh.',
    promptModifier: 'modern tech entrepreneur headshot, wearing a premium fitted t-shirt and casual blazer, blurred modern open-plan office background with glass and greenery, bright daylight, approachable yet professional, 8k',
    iconName: 'Monitor',
    colorFrom: 'from-blue-500',
    colorTo: 'to-cyan-500',
    previewUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'industrial-pro',
    name: 'Industrial Pro',
    category: 'Professional',
    description: 'Rugged professional look, welding/construction aesthetic.',
    promptModifier: 'industrial professional headshot, wearing rugged workwear, leather jacket or safety gear, background of a modern factory or industrial site with sparks or steel structures, dramatic contrast lighting, gritty and strength, 8k',
    iconName: 'HardHat',
    colorFrom: 'from-orange-600',
    colorTo: 'to-red-700',
    previewUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'master-chef',
    name: 'Master Chef',
    category: 'Professional',
    description: 'Culinary expert in a high-end kitchen environment.',
    promptModifier: 'professional chef portrait, wearing pristine white chef jacket and hat, busy blurred high-end restaurant kitchen background, confident smile, warm professional lighting, 8k',
    iconName: 'ChefHat',
    colorFrom: 'from-red-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'firefighter',
    name: 'Firefighter',
    category: 'Professional',
    description: 'Heroic portrait in full gear.',
    promptModifier: 'firefighter portrait, wearing heavy turnout gear and helmet, background of a fire station or fire truck, heroic dramatic lighting, brave and determined expression, 8k',
    iconName: 'Flame',
    colorFrom: 'from-orange-600',
    colorTo: 'to-red-800',
    previewUrl: 'https://images.unsplash.com/photo-1555436169-20e93ea9a7ff?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'military-tactical',
    name: 'Army Tactical',
    category: 'Professional',
    description: 'Tactical camouflage uniform, rugged military setting.',
    promptModifier: 'military portrait, wearing modern tactical camouflage combat uniform (OCP) with velcro patches, blurred military base background, tough and disciplined expression, high contrast cinematic lighting, 8k',
    iconName: 'Shield',
    colorFrom: 'from-green-700',
    colorTo: 'to-emerald-900',
    previewUrl: 'https://images.unsplash.com/photo-1542359218-e3624f2b9347?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'military-dress',
    name: 'Dress Uniform',
    category: 'Professional',
    description: 'Formal full dress uniform with medals and honors.',
    promptModifier: 'formal military headshot, wearing full dress uniform (dark navy or black) with medals and ribbons, crisp white shirt, clean professional studio background (neutral or flag), dignified and authoritative, 8k',
    iconName: 'Award',
    colorFrom: 'from-slate-800',
    colorTo: 'to-blue-900',
    previewUrl: 'https://images.unsplash.com/photo-1580128660010-fd027e1e587a?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'air-force-pilot',
    name: 'Air Force Pilot',
    category: 'Professional',
    description: 'Flight suit, airfield/hangar background, heroic vibe.',
    promptModifier: 'air force pilot portrait, wearing olive drab or sage green flight suit with squadron patches, blurred airfield or hangar background with aircraft bokeh, heroic lighting, confident, 8k',
    iconName: 'Plane',
    colorFrom: 'from-sky-600',
    colorTo: 'to-blue-800',
    previewUrl: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'navy-officer',
    name: 'Navy Officer',
    category: 'Professional',
    description: 'White naval service uniform, maritime background.',
    promptModifier: 'navy officer portrait, wearing pristine white naval service uniform with shoulder boards, background of a blurred naval ship deck or ocean horizon, bright daylight, authoritative and disciplined, 8k',
    iconName: 'Anchor',
    colorFrom: 'from-blue-500',
    colorTo: 'to-slate-200',
    previewUrl: 'https://images.unsplash.com/photo-1454589938531-1554a9d80324?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'cricket-captain',
    name: 'Cricket Captain',
    category: 'Professional',
    description: 'National team jersey in a stadium setting.',
    promptModifier: 'professional cricket player portrait, wearing blue national team jersey, background of a packed cricket stadium with floodlights, athletic build, determined expression, cinematic sports lighting, 8k',
    iconName: 'Trophy',
    colorFrom: 'from-blue-600',
    colorTo: 'to-cyan-500',
    previewUrl: 'https://images.unsplash.com/photo-1631194758628-71ec7c35137e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- POLITICAL (18 Styles) ---
  {
    id: 'rashtriya-neta',
    name: 'Rashtriya Neta',
    category: 'Political',
    description: 'Classic leader look with white Kurta and Nehru Jacket.',
    promptModifier: 'indian political leader portrait, wearing crisp white khadi kurta pajama and a sleeveless nehru jacket (modi coat), folded hands namaste pose optional, blurred background of indian parliament or political rally, authoritative, dignified, photorealistic 8k',
    iconName: 'Landmark',
    colorFrom: 'from-orange-500',
    colorTo: 'to-green-600',
    previewUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'party-bjp',
    name: 'Saffron Leader',
    category: 'Political',
    description: 'Nationalist look with Saffron jacket and Lotus symbol style.',
    promptModifier: 'indian political portrait, bjp party style, wearing crisp white kurta pajama and saffron (orange) nehru jacket, saffron scarf with lotus badge, blurred background of election rally with saffron flags, authoritative, confident, photorealistic 8k',
    iconName: 'Flower2',
    colorFrom: 'from-orange-500',
    colorTo: 'to-orange-700',
    previewUrl: 'https://images.unsplash.com/photo-1558981396-5fcf84bba14b?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-congress',
    name: 'Tricolor Vision',
    category: 'Political',
    description: 'Classic Khadi look with Tricolor scarf.',
    promptModifier: 'indian political portrait, congress party style, wearing traditional white khadi kurta, tricolor scarf (tiranga) draped around neck, background of political stage with tricolor flags, statesman-like, calm and dignified, 8k',
    iconName: 'Hand',
    colorFrom: 'from-green-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1590086782792-42dd2350140d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-aap',
    name: 'Aam Aadmi',
    category: 'Political',
    description: 'Simple shirt and white cap common man look.',
    promptModifier: 'indian political portrait, aam aadmi party style, wearing simple checked shirt or sweater, white gandhi topi (cap) with text, blurred city background, approachable, honest common man vibe, 8k',
    iconName: 'Megaphone',
    colorFrom: 'from-blue-500',
    colorTo: 'to-slate-500',
    previewUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'saffron-pride',
    name: 'Saffron Pride',
    category: 'Political',
    description: 'Cultural nationalist look with traditional saffron attire.',
    promptModifier: 'indian cultural political leader, wearing traditional kurta with a saffron (orange) angavastram or scarf around neck, tilak on forehead, confident and charismatic, warm golden lighting, background suggestive of temple architecture or sunset, 8k',
    iconName: 'Flag',
    colorFrom: 'from-orange-600',
    colorTo: 'to-amber-700',
    previewUrl: 'https://images.unsplash.com/photo-1596706037000-058867fb44f6?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'yuva-morcha',
    name: 'Yuva Morcha',
    category: 'Political',
    description: 'Dynamic youth leader with a modern campaign vibe.',
    promptModifier: 'young indian political leader, wearing a crisp white shirt with rolled sleeves and a tricolor sash or badge, modern grooming, background of a busy indian campaign crowd, energetic and visionary, 8k',
    iconName: 'Megaphone',
    colorFrom: 'from-blue-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-shivsena',
    name: 'Maratha Pride',
    category: 'Political',
    description: 'Fierce leader look with saffron scarf and traditional attire.',
    promptModifier: 'indian political leader portrait, shiv sena style, wearing crisp white kurta and bright saffron scarf over shoulders, intense and determined expression, maratha warrior vibe, blurred background of rally with orange flags and bow-arrow symbols, energetic lighting, 8k',
    iconName: 'Target',
    colorFrom: 'from-orange-600',
    colorTo: 'to-red-600',
    previewUrl: 'https://images.unsplash.com/photo-1558507308-20d440938f4d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-tmc',
    name: 'Bengal Grassroots',
    category: 'Political',
    description: 'Simple white cultural attire, approachable grassroots leader.',
    promptModifier: 'indian political portrait, west bengal tmc style, wearing simple white cotton kurta or saree, approachable and humble expression, background of greenery or grassroots rally with flower symbols, soft natural daylight, 8k',
    iconName: 'Flower',
    colorFrom: 'from-green-500',
    colorTo: 'to-emerald-400',
    previewUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-dmk',
    name: 'Dravidian Sun',
    category: 'Political',
    description: 'South Indian political attire with Angavastram.',
    promptModifier: 'south indian political leader portrait, wearing crisp white shirt and veshti (dhoti), draping a towel (angavastram) with red and black borders over shoulder, dignified and scholarly, background of rising sun or chennai skyline, 8k',
    iconName: 'Sunrise',
    colorFrom: 'from-red-600',
    colorTo: 'to-slate-900',
    previewUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-sp',
    name: 'Samajwadi Red',
    category: 'Political',
    description: 'Signature red cap and simple socialist attire.',
    promptModifier: 'indian political portrait, samajwadi party style, wearing white kurta pajama and signature red cap, friendly and youthful expression, background of rural india or cycle rally, warm lighting, 8k',
    iconName: 'Bike',
    colorFrom: 'from-red-500',
    colorTo: 'to-green-500',
    previewUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-tdp',
    name: 'Yellow Army',
    category: 'Political',
    description: 'Professional look with signature yellow scarf.',
    promptModifier: 'indian political leader portrait, telugu desam party style, wearing professional dress shirt with a bright yellow scarf or shawl, intelligent and tech-savvy vibe, background of modern city development, 8k',
    iconName: 'Zap',
    colorFrom: 'from-yellow-400',
    colorTo: 'to-amber-400',
    previewUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-cpim',
    name: 'Communist Star',
    category: 'Political',
    description: 'Red themed intellectual and revolutionary leader look.',
    promptModifier: 'indian political leader, communist party style, wearing simple red shirt or white kurta with red scarf, intellectual vibe, background of rally with red flags, determined and serious, 8k',
    iconName: 'Star',
    colorFrom: 'from-red-700',
    colorTo: 'to-red-900',
    previewUrl: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-bsp',
    name: 'Blue Elephant',
    category: 'Political',
    description: 'Blue themed attire representing social justice.',
    promptModifier: 'indian political leader, bahujan samaj party style, wearing blue jacket or scarf over white attire, dignified and stern expression, background of political stage with blue flags, authoritative, 8k',
    iconName: 'Hexagon',
    colorFrom: 'from-blue-600',
    colorTo: 'to-blue-800',
    previewUrl: 'https://images.unsplash.com/photo-1555819206-8b30349f7d4d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-ncp',
    name: 'Clock Warrior',
    category: 'Political',
    description: 'Maharashtra political style with tricolor scarf.',
    promptModifier: 'indian political leader portrait, ncp style, wearing white kurta with distinctive tricolor scarf, maratha leader vibe, background of political gathering, experienced and confident, 8k',
    iconName: 'Watch',
    colorFrom: 'from-blue-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1595013066606-2542a1532130?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-aiadmk',
    name: 'Two Leaves',
    category: 'Political',
    description: 'Tamil Nadu political style with green accents.',
    promptModifier: 'south indian political leader, aiadmk style, wearing white shirt with green border dhoti or scarf, respectful greeting pose, background of chennai marina beach or rally, 8k',
    iconName: 'Leaf',
    colorFrom: 'from-green-500',
    colorTo: 'to-emerald-600',
    previewUrl: 'https://images.unsplash.com/photo-1582233479366-6d38bc390a08?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-inld',
    name: 'Green Turban',
    category: 'Political',
    description: 'Haryana/Punjab political style with green turban.',
    promptModifier: 'north indian political leader, haryana style, wearing white kurta and bright green turban (pagri), sturdy built, background of rural gathering or fields, earthy and strong, 8k',
    iconName: 'Sprout',
    colorFrom: 'from-green-600',
    colorTo: 'to-green-800',
    previewUrl: 'https://images.unsplash.com/photo-1585869062327-1473722d3667?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-akali',
    name: 'Punjab Pride',
    category: 'Political',
    description: 'Traditional Akali style with blue or orange turban.',
    promptModifier: 'punjabi political leader, akali dal style, wearing dark blue or saffron turban and flowing beard, religious and political authority, background of golden temple or rally, 8k',
    iconName: 'Sunrise',
    colorFrom: 'from-blue-700',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1564292150965-4f3697e0662d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'party-jmm',
    name: 'Tribal Archer',
    category: 'Political',
    description: 'Jharkhand political style honoring tribal roots.',
    promptModifier: 'indian tribal political leader, jmm style, wearing white kurta with green gamcha or scarf, indigenous features, background of forest or tribal rally, humble yet strong, 8k',
    iconName: 'Target',
    colorFrom: 'from-green-700',
    colorTo: 'to-emerald-800',
    previewUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- CASUAL (18 Styles) ---
  {
    id: 'casual-outdoor',
    name: 'Casual Outdoor',
    category: 'Casual',
    description: 'Relaxed natural vibe in a park or garden.',
    promptModifier: 'relaxed outdoor portrait, wearing comfortable casual clothing (t-shirt or polo), soft natural lighting, blurred nature background with trees, approachable and friendly, 8k',
    iconName: 'TreeDeciduous',
    colorFrom: 'from-green-500',
    colorTo: 'to-emerald-600',
    previewUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'outdoor-natural',
    name: 'Outdoor Natural',
    category: 'Casual',
    description: 'Golden hour lighting, blurred park or city background.',
    promptModifier: 'outdoor professional portrait, natural golden hour lighting, wearing smart casual business attire, soft bokeh background of a city park or nature, warm tones, friendly and charismatic, photorealistic 8k',
    iconName: 'Sun',
    colorFrom: 'from-amber-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'casual-jeans',
    name: 'Jeans & Top',
    category: 'Casual',
    description: 'Relaxed modern casual wear with jeans and a stylish top.',
    promptModifier: 'casual lifestyle portrait, wearing fitted blue jeans and a stylish casual top or blouse, relaxed posture, bright natural lighting, modern lifestyle background, approachable and trendy, 8k',
    iconName: 'User',
    colorFrom: 'from-blue-400',
    colorTo: 'to-indigo-500',
    previewUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'start-up-coffee',
    name: 'Coffee Shop Vibes',
    category: 'Casual',
    description: 'Relaxed, working at a cafe, approachable and dynamic.',
    promptModifier: 'casual professional portrait inside a high-end coffee shop, wearing stylish knitwear, blurred background of cafe interior, warm ambient lighting, looking at camera, approachable and authentic, 8k',
    iconName: 'Coffee',
    colorFrom: 'from-emerald-500',
    colorTo: 'to-teal-600',
    previewUrl: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'campus-casual',
    name: 'Campus Casual',
    category: 'Casual',
    description: 'Relaxed student vibe with hoodies or casual wear on campus.',
    promptModifier: 'relaxed college student portrait, wearing stylish hoodie or premium casual sweatshirt, blurred university campus background with brick buildings and greenery, soft natural lighting, youthful and friendly, 8k',
    iconName: 'BookOpen',
    colorFrom: 'from-amber-400',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'future-intern',
    name: 'Future Intern',
    category: 'Casual',
    description: 'Smart-casual look ready for internships and interviews.',
    promptModifier: 'ambitious college student headshot, wearing smart casual attire (polo shirt or blouse), blurred modern university library background with books and glass, bright lighting, confident and eager expression, 8k',
    iconName: 'Laptop',
    colorFrom: 'from-sky-400',
    colorTo: 'to-blue-600',
    previewUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'minimalist-white',
    name: 'Minimalist White',
    category: 'Casual',
    description: 'Clean, high-key white background for a modern look.',
    promptModifier: 'minimalist modern headshot, wearing solid color clothing, pure white studio background, high-key lighting, clean and sharp, fresh and modern look, 8k',
    iconName: 'Feather',
    colorFrom: 'from-slate-200',
    colorTo: 'to-slate-400',
    previewUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'beach-vibe',
    name: 'Beach Vibe',
    category: 'Casual',
    description: 'Summer linen aesthetic with ocean background.',
    promptModifier: 'casual beach portrait, wearing light linen shirt, background of ocean and blue sky, bright natural sunlight, relaxed summer vibe, windswept hair, 8k',
    iconName: 'Waves',
    colorFrom: 'from-cyan-400',
    colorTo: 'to-blue-400',
    previewUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'winter-cozy',
    name: 'Winter Cozy',
    category: 'Casual',
    description: 'Warm sweater and snowy background.',
    promptModifier: 'winter portrait, wearing cozy knit sweater and scarf, background of snowy trees or winter street, soft overcast lighting, warm and comfortable vibe, 8k',
    iconName: 'Snowflake',
    colorFrom: 'from-blue-200',
    colorTo: 'to-slate-300',
    previewUrl: 'https://images.unsplash.com/photo-1516724562728-afc824a36e84?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'gym-fitness',
    name: 'Gym Fitness',
    category: 'Casual',
    description: 'Athletic wear in a modern gym setting.',
    promptModifier: 'fitness portrait, wearing premium athletic sportswear, background of modern gym with equipment, energetic lighting, fit and healthy look, 8k',
    iconName: 'Dumbbell',
    colorFrom: 'from-red-500',
    colorTo: 'to-slate-800',
    previewUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'urban-street',
    name: 'Urban Street',
    category: 'Casual',
    description: 'Edgy streetwear style with city background.',
    promptModifier: 'urban streetwear portrait, wearing stylish street fashion (hoodie/jacket), background of city alley with graffiti art or textured wall, cool dramatic lighting, edgy vibe, 8k',
    iconName: 'Footprints',
    colorFrom: 'from-slate-700',
    colorTo: 'to-black',
    previewUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'library-focus',
    name: 'Library Studious',
    category: 'Casual',
    description: 'Intellectual vibe with bookshelf background.',
    promptModifier: 'studious portrait, smart casual dress, background of library bookshelves filled with books, warm quiet lighting, glasses optional, intellectual and focused, 8k',
    iconName: 'BookOpen',
    colorFrom: 'from-amber-700',
    colorTo: 'to-brown-800',
    previewUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'travel-blogger',
    name: 'Travel Blogger',
    category: 'Casual',
    description: 'Adventurous look with famous landmark background.',
    promptModifier: 'travel lifestyle portrait, wearing casual travel clothes with backpack strap visible, background of blurred famous landmark (e.g. Eiffel tower or mountain), bright sunny lighting, adventurous spirit, 8k',
    iconName: 'MapPin',
    colorFrom: 'from-sky-400',
    colorTo: 'to-green-400',
    previewUrl: 'https://images.unsplash.com/photo-1500835556837-99ac94a94552?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'home-office',
    name: 'Home Office',
    category: 'Casual',
    description: 'Professional yet comfortable work-from-home look.',
    promptModifier: 'work from home portrait, wearing comfortable smart casual, background of stylish home office with plants and computer monitor, soft window lighting, modern remote work vibe, 8k',
    iconName: 'Laptop',
    colorFrom: 'from-slate-400',
    colorTo: 'to-blue-400',
    previewUrl: 'https://images.unsplash.com/photo-1593642532744-d377ab507dc8?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'Casual',
    description: 'Warm, romantic golden hour backlight.',
    promptModifier: 'sunset portrait, casual summer dress, strong golden hour backlighting (rim light), background of open field or beach at dusk, warm orange and purple tones, dreamy and romantic, 8k',
    iconName: 'Sun',
    colorFrom: 'from-orange-500',
    colorTo: 'to-purple-600',
    previewUrl: 'https://images.unsplash.com/photo-1495615080073-6b89c98beddb?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'rainy-day',
    name: 'Rainy Day',
    category: 'Casual',
    description: 'Moody, cinematic look with rain and umbrella.',
    promptModifier: 'cinematic rain portrait, wearing raincoat or trench coat, holding umbrella, background of rainy city street with reflections, moody blue lighting, emotional and atmospheric, 8k',
    iconName: 'CloudRain',
    colorFrom: 'from-slate-600',
    colorTo: 'to-blue-800',
    previewUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'road-trip',
    name: 'Road Trip',
    category: 'Casual',
    description: 'Freedom vibe inside a car or convertible.',
    promptModifier: 'lifestyle car portrait, sitting in driver seat of a car or convertible, background of passing road or scenery, natural light coming through window, sunglasses optional, cool travel vibe, 8k',
    iconName: 'Car',
    colorFrom: 'from-red-500',
    colorTo: 'to-slate-800',
    previewUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'garden-relax',
    name: 'Garden Relax',
    category: 'Casual',
    description: 'Peaceful portrait in a blooming garden.',
    promptModifier: 'garden portrait, wearing light floral or pastel clothing, background of lush green garden with colorful flowers, soft dappled sunlight, peaceful and happy expression, 8k',
    iconName: 'Flower',
    colorFrom: 'from-green-400',
    colorTo: 'to-pink-400',
    previewUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- FORMAL EVENTS (18 Styles) ---
  {
    id: 'party-glam',
    name: 'Gala & Party',
    category: 'Formal Events',
    description: 'Elegant evening wear, festive luxury atmosphere.',
    promptModifier: 'glamorous evening portrait, wearing elegant formal party attire or cocktail dress/tuxedo, blurred luxury ballroom or party background with warm bokeh lights, festive and sophisticated, high fashion, 8k',
    iconName: 'Sparkles',
    colorFrom: 'from-rose-500',
    colorTo: 'to-pink-600',
    previewUrl: 'https://images.unsplash.com/photo-1533227297464-60f95d904055?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'party-mode',
    name: 'Party Mode',
    category: 'Formal Events',
    description: 'Festive, energetic, and full of celebration.',
    promptModifier: 'fun party headshot, wearing stylish party clothes, background with colorful confetti and balloons, vibrant dynamic lighting, happy and energetic expression, celebration atmosphere, 8k',
    iconName: 'PartyPopper',
    colorFrom: 'from-fuchsia-500',
    colorTo: 'to-yellow-500',
    previewUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'graduation-day',
    name: 'Graduation Day',
    category: 'Formal Events',
    description: 'Celebrating academic success in cap and gown.',
    promptModifier: 'graduation portrait, wearing academic graduation cap and gown, holding a diploma scroll, blurred university ceremony background, proud and happy expression, warm golden hour lighting, high quality 8k',
    iconName: 'GraduationCap',
    colorFrom: 'from-indigo-500',
    colorTo: 'to-purple-700',
    previewUrl: 'https://images.unsplash.com/photo-1535982330050-f1c2fb9705f0?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'red-carpet',
    name: 'Red Carpet',
    category: 'Formal Events',
    description: 'Celebrity style with camera flashes background.',
    promptModifier: 'celebrity red carpet portrait, wearing luxury tuxedo or evening gown, background of paparazzi camera flashes and red carpet, dramatic high-contrast lighting, confident star pose, 8k',
    iconName: 'Camera',
    colorFrom: 'from-red-600',
    colorTo: 'to-rose-800',
    previewUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'black-tie',
    name: 'Black Tie',
    category: 'Formal Events',
    description: 'Strictly formal dinner jacket and bow tie elegance.',
    promptModifier: 'black tie formal portrait, wearing classic black tuxedo with bow tie and white shirt, background of elegant dark interior, sophisticated rim lighting, james bond vibe, 8k',
    iconName: 'Shirt',
    colorFrom: 'from-black',
    colorTo: 'to-slate-800',
    previewUrl: 'https://images.unsplash.com/photo-1504199367641-aba8151af406?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'cocktail-hour',
    name: 'Cocktail Hour',
    category: 'Formal Events',
    description: 'Chic evening social vibe on a rooftop.',
    promptModifier: 'cocktail party portrait, wearing chic cocktail attire, holding a drink (optional), background of a rooftop bar at twilight with city lights, sophisticated and social atmosphere, 8k',
    iconName: 'Wine',
    colorFrom: 'from-purple-500',
    colorTo: 'to-indigo-500',
    previewUrl: 'https://images.unsplash.com/photo-1572061489701-443b7e289899?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'new-years-eve',
    name: 'New Year\'s Eve',
    category: 'Formal Events',
    description: 'Sparkling celebration with fireworks background.',
    promptModifier: 'new years eve portrait, wearing sparkly party outfit, background of night sky with fireworks, bright festive lighting, excited and happy expression, celebration, 8k',
    iconName: 'Sparkles',
    colorFrom: 'from-yellow-400',
    colorTo: 'to-purple-900',
    previewUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'birthday-bash',
    name: 'Birthday Bash',
    category: 'Formal Events',
    description: 'Fun birthday vibe with balloons and cake.',
    promptModifier: 'birthday celebration portrait, wearing party clothes, background filled with colorful balloons and decorations, bright happy lighting, joyful expression, 8k',
    iconName: 'Gift',
    colorFrom: 'from-pink-400',
    colorTo: 'to-cyan-400',
    previewUrl: 'https://images.unsplash.com/photo-1530103862676-de3c9da59af7?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'award-night',
    name: 'Award Night',
    category: 'Formal Events',
    description: 'Holding a trophy in a spotlight moment.',
    promptModifier: 'award winner portrait, wearing formal attire, holding a gold trophy, background of stage curtains and spotlights, proud and successful expression, dramatic lighting, 8k',
    iconName: 'Award',
    colorFrom: 'from-yellow-500',
    colorTo: 'to-amber-600',
    previewUrl: 'https://images.unsplash.com/photo-1622642552697-39281561571d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'garden-party',
    name: 'Garden Party',
    category: 'Formal Events',
    description: 'Semi-formal daytime event in a garden.',
    promptModifier: 'garden party portrait, wearing semi-formal summer suit or floral dress, background of manicured lawn and white tents, bright soft daylight, elegant social vibe, 8k',
    iconName: 'Flower',
    colorFrom: 'from-green-400',
    colorTo: 'to-emerald-500',
    previewUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0202128?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'prom-night',
    name: 'Prom Night',
    category: 'Formal Events',
    description: 'High school formal elegance with corsage.',
    promptModifier: 'prom night portrait, wearing tuxedo or prom dress with corsage, background of decorated school gym or ballroom, romantic lighting, youthful elegance, 8k',
    iconName: 'Crown',
    colorFrom: 'from-purple-400',
    colorTo: 'to-pink-500',
    previewUrl: 'https://images.unsplash.com/photo-1550596334-7bb40a71b6bc?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'opera-night',
    name: 'Opera Night',
    category: 'Formal Events',
    description: 'Sophisticated luxury in a grand theater box.',
    promptModifier: 'luxury opera portrait, wearing high-end formal wear and jewelry, background of grand theater box with red velvet curtains, dramatic warm lighting, aristocratic vibe, 8k',
    iconName: 'Music',
    colorFrom: 'from-red-800',
    colorTo: 'to-black',
    previewUrl: 'https://images.unsplash.com/photo-1514525253440-b393452e8d26?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'wedding-guest',
    name: 'Wedding Guest',
    category: 'Formal Events',
    description: 'Best dressed guest at a wedding reception.',
    promptModifier: 'wedding guest portrait, wearing stylish formal attire, background of wedding reception tables with flowers, soft romantic lighting, happy and social, 8k',
    iconName: 'Heart',
    colorFrom: 'from-pink-300',
    colorTo: 'to-rose-400',
    previewUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'champagne-toast',
    name: 'Champagne Toast',
    category: 'Formal Events',
    description: 'Raising a glass in celebration.',
    promptModifier: 'celebration portrait, raising a glass of champagne, wearing party attire, background of sparkling lights, joyous expression, focus on face and glass, 8k',
    iconName: 'Wine',
    colorFrom: 'from-yellow-200',
    colorTo: 'to-amber-300',
    previewUrl: 'https://images.unsplash.com/photo-1516600164266-f3b8166ae679?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'disco-fever',
    name: 'Disco Fever',
    category: 'Formal Events',
    description: 'Retro 70s party vibe with disco ball.',
    promptModifier: 'retro disco portrait, 1970s fashion style, background with disco ball and colored lights, funky energetic vibe, flash photography style, 8k',
    iconName: 'Disc',
    colorFrom: 'from-fuchsia-600',
    colorTo: 'to-purple-700',
    previewUrl: 'https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'yacht-party',
    name: 'Yacht Party',
    category: 'Formal Events',
    description: 'Luxury white party on a yacht deck.',
    promptModifier: 'luxury yacht party portrait, wearing all-white upscale casual clothing, background of yacht deck and blue ocean, bright sunlight, wealthy lifestyle vibe, 8k',
    iconName: 'Anchor',
    colorFrom: 'from-blue-400',
    colorTo: 'to-cyan-200',
    previewUrl: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'club-night',
    name: 'Club Night',
    category: 'Formal Events',
    description: 'Edgy nightlife portrait with neon lasers.',
    promptModifier: 'nightclub portrait, stylish clubwear, background of dark club with laser lights and fog, moody neon lighting, cool and edgy expression, 8k',
    iconName: 'Speaker',
    colorFrom: 'from-violet-600',
    colorTo: 'to-indigo-900',
    previewUrl: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'masquerade',
    name: 'Masquerade',
    category: 'Formal Events',
    description: 'Mysterious elegance with a venetian mask.',
    promptModifier: 'masquerade ball portrait, wearing formal attire and holding an elegant venetian mask, background of dark ballroom with chandeliers, mysterious and alluring, dramatic lighting, 8k',
    iconName: 'Eye',
    colorFrom: 'from-purple-800',
    colorTo: 'to-black',
    previewUrl: 'https://images.unsplash.com/photo-1505247964246-1f0a90443c36?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- CULTURAL (18 Styles) ---
  {
    id: 'royal-groom',
    name: 'Royal Groom',
    category: 'Cultural',
    description: 'Traditional Sherwani and Turban for a majestic wedding look.',
    promptModifier: 'traditional indian groom portrait, wearing regal sherwani with intricate embroidery and a safa (turban), blurred wedding mandap background, royal stance, warm golden cinematic lighting, 8k',
    iconName: 'Crown',
    colorFrom: 'from-amber-600',
    colorTo: 'to-yellow-800',
    previewUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'royal-bride',
    name: 'Royal Bride',
    category: 'Cultural',
    description: 'Exquisite Lehenga and Jewelry for the perfect bridal portrait.',
    promptModifier: 'traditional indian bride portrait, wearing heavily embroidered red bridal lehenga and traditional gold jewelry (matha patti, nath, necklace), professional bridal makeup, blurred floral wedding background, elegant and stunning, 8k',
    iconName: 'Heart',
    colorFrom: 'from-red-600',
    colorTo: 'to-rose-800',
    previewUrl: 'https://images.unsplash.com/photo-1594125315357-1906a6b5791c?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'sikh-wedding',
    name: 'Sikh Wedding',
    category: 'Cultural',
    description: 'Regal Turban and vibrant traditional attire.',
    promptModifier: 'traditional sikh wedding portrait, wearing luxurious sherwani with turban (dastar) or vibrant bridal suit with heavy gold jewelry, blurred background of a Gurudwara with golden details, bright daylight, regal and spiritual, 8k',
    iconName: 'Sunrise',
    colorFrom: 'from-orange-500',
    colorTo: 'to-red-500',
    previewUrl: 'https://images.unsplash.com/photo-1636306660146-a4f6d3447990?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'christian-wedding',
    name: 'Christian Wedding',
    category: 'Cultural',
    description: 'Classic White Gown and Tuxedo elegance.',
    promptModifier: 'classic christian wedding portrait, wearing white bridal gown with lace details or black tuxedo, blurred background of a church interior or floral archway, soft ethereal lighting, romantic and elegant, 8k',
    iconName: 'Church',
    colorFrom: 'from-slate-100',
    colorTo: 'to-slate-300',
    previewUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'muslim-wedding',
    name: 'Muslim Wedding',
    category: 'Cultural',
    description: 'Elegant Nikah look with traditional richness.',
    promptModifier: 'traditional muslim wedding portrait, wearing elegant sherwani or bridal sharara with hijab styling, background of intricate islamic geometric patterns or floral decor, cinematic lighting, dignified and graceful, 8k',
    iconName: 'Moon',
    colorFrom: 'from-emerald-600',
    colorTo: 'to-teal-800',
    previewUrl: 'https://images.unsplash.com/photo-1587271407850-8d4389188265?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'sari-elegance',
    name: 'Elegant Sari',
    category: 'Cultural',
    description: 'Traditional and sophisticated saree for a cultural statement.',
    promptModifier: 'traditional elegant portrait, wearing a beautiful embroidered saree with matching blouse, cultural aesthetic, soft glam makeup, professional studio lighting, refined and graceful, 8k',
    iconName: 'Flower2',
    colorFrom: 'from-pink-600',
    colorTo: 'to-orange-600',
    previewUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'haldi-ceremony',
    name: 'Haldi Ceremony',
    category: 'Cultural',
    description: 'Joyful yellow festive look with turmeric and marigolds.',
    promptModifier: 'haldi ceremony portrait, wearing yellow ethnic attire (kurta or saree), face playfully smeared with turmeric (haldi) paste, background of marigold flower decorations, bright daylight, happy and festive expression, 8k',
    iconName: 'Gem',
    colorFrom: 'from-yellow-400',
    colorTo: 'to-amber-500',
    previewUrl: 'https://images.unsplash.com/photo-1622765324545-2e650d535352?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'diwali-lights',
    name: 'Diwali Glow',
    category: 'Cultural',
    description: 'Warm, festive look with traditional lamps and golden lighting.',
    promptModifier: 'traditional diwali festival portrait, wearing elegant indian ethnic wear (sherwani or saree), blurred background of glowing diyas and marigold decorations, warm candlelight atmosphere, spiritual and celebratory, 8k',
    iconName: 'Flame',
    colorFrom: 'from-orange-500',
    colorTo: 'to-yellow-600',
    previewUrl: 'https://images.unsplash.com/photo-1605218427368-35b80a373b88?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'holi-colors',
    name: 'Holi Splash',
    category: 'Cultural',
    description: 'Vibrant, colorful, and energetic festival of colors.',
    promptModifier: 'holi festival portrait, wearing white ethnic clothes with artistic splashes of colorful powder (gulal) on face, background of vibrant color clouds, bright energetic lighting, happy expression, 8k',
    iconName: 'Palette',
    colorFrom: 'from-pink-500',
    colorTo: 'to-yellow-500',
    previewUrl: 'https://images.unsplash.com/photo-1583096114844-065dc6726220?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'garba-night',
    name: 'Garba Night',
    category: 'Cultural',
    description: 'Colorful Navratri attire with oxidized jewelry.',
    promptModifier: 'navratri garba portrait, wearing colorful traditional chaniya choli or kediyu with mirror work and oxidized silver jewelry, background of festival night with dandiya sticks, dynamic lighting, energetic, 8k',
    iconName: 'Music',
    colorFrom: 'from-pink-600',
    colorTo: 'to-purple-600',
    previewUrl: 'https://images.unsplash.com/photo-1508215885820-4585e56135c8?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'south-indian-bride',
    name: 'South Indian Bride',
    category: 'Cultural',
    description: 'Rich Kanjeevaram saree and temple jewelry.',
    promptModifier: 'south indian bride portrait, wearing rich silk kanjeevaram saree and traditional temple gold jewelry, jasmine flowers (gajra) in hair, background of traditional temple architecture, golden warm lighting, 8k',
    iconName: 'Gem',
    colorFrom: 'from-yellow-600',
    colorTo: 'to-red-600',
    previewUrl: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'bengali-saree',
    name: 'Bengali Saree',
    category: 'Cultural',
    description: 'Traditional red and white saree with big bindi.',
    promptModifier: 'traditional bengali portrait, wearing white saree with red border (lal paar saree), large red bindi, gold jewelry, background of durga puja festivity, cultural and elegant, 8k',
    iconName: 'Feather',
    colorFrom: 'from-red-500',
    colorTo: 'to-white',
    previewUrl: 'https://images.unsplash.com/photo-1586078335036-bd885368593a?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'eid-mubarak',
    name: 'Eid Mubarak',
    category: 'Cultural',
    description: 'Festive Pathani or Abaya look for Eid.',
    promptModifier: 'eid festival portrait, wearing crisp new pathani suit or elegant abaya, background of moonlit night or decorated home, peaceful and joyful expression, soft cool lighting, 8k',
    iconName: 'Moon',
    colorFrom: 'from-emerald-500',
    colorTo: 'to-cyan-500',
    previewUrl: 'https://images.unsplash.com/photo-1534349762913-96c87130f6aa?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'christmas-joy',
    name: 'Christmas Joy',
    category: 'Cultural',
    description: 'Festive red and white holiday spirit.',
    promptModifier: 'christmas portrait, wearing cozy red holiday sweater or santa hat, background of decorated christmas tree with twinkling lights, warm cozy lighting, happy festive vibe, 8k',
    iconName: 'Gift',
    colorFrom: 'from-red-600',
    colorTo: 'to-green-700',
    previewUrl: 'https://images.unsplash.com/photo-1545224144-b38cd309ef69?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'onam-fest',
    name: 'Onam Fest',
    category: 'Cultural',
    description: 'Kerala traditional white and gold attire.',
    promptModifier: 'onam festival portrait, wearing traditional kerala kasavu saree or mundu (white with gold border), background of floral rangoli (pookalam), bright natural light, simple elegance, 8k',
    iconName: 'Sun',
    colorFrom: 'from-yellow-100',
    colorTo: 'to-yellow-300',
    previewUrl: 'https://images.unsplash.com/photo-1510590337019-5ef2d3977e2e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'lohri-fire',
    name: 'Lohri Fire',
    category: 'Cultural',
    description: 'Winter folk festival with bonfire warmth.',
    promptModifier: 'lohri festival portrait, wearing colorful punjabi ethnic wear, background of bonfire at night, warm fire glow on face, energetic and happy expression, folk culture, 8k',
    iconName: 'Flame',
    colorFrom: 'from-orange-500',
    colorTo: 'to-red-700',
    previewUrl: 'https://images.unsplash.com/photo-1514315384763-ba401779410f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'ganesh-chaturthi',
    name: 'Ganesh Chaturthi',
    category: 'Cultural',
    description: 'Devotional festive look with saffron and red hues.',
    promptModifier: 'ganesh chaturthi portrait, wearing traditional indian kurta or saree in orange/red, red tilak on forehead, background of ganesh idol or decorations, spiritual and celebratory, 8k',
    iconName: 'Flower',
    colorFrom: 'from-orange-500',
    colorTo: 'to-red-500',
    previewUrl: 'https://images.unsplash.com/photo-1631026601618-502a90098f48?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'tribal-tradition',
    name: 'Tribal Tradition',
    category: 'Cultural',
    description: 'Indigenous cultural attire with beads and feathers.',
    promptModifier: 'tribal cultural portrait, wearing traditional indigenous clothing with beadwork and feather headgear, background of nature or tribal village, strong and proud expression, authentic cultural representation, 8k',
    iconName: 'Feather',
    colorFrom: 'from-amber-700',
    colorTo: 'to-brown-600',
    previewUrl: 'https://images.unsplash.com/photo-1520633854839-44585de79f22?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- CREATIVE (18 Styles) ---
  {
    id: 'fashion-model',
    name: 'Top Model (F)',
    category: 'Creative',
    description: 'High-fashion magazine aesthetic, trendy and glamorous.',
    promptModifier: 'high-fashion editorial portrait, female model aesthetic, wearing trendy designer clothing, dramatic fashion lighting, sleek hair and makeup, neutral high-end studio background, confident and fierce expression, vogue style, 8k resolution',
    iconName: 'Crown',
    colorFrom: 'from-fuchsia-500',
    colorTo: 'to-purple-600',
    previewUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'artist-loft',
    name: 'Artist Loft',
    category: 'Creative',
    description: 'Creative workspace with natural light and artistic vibes.',
    promptModifier: 'creative artist headshot, wearing stylish casual attire, background of a bright artist loft studio with paintings and easels, soft natural window light, artistic and expressive, 8k',
    iconName: 'Palette',
    colorFrom: 'from-pink-500',
    colorTo: 'to-orange-400',
    previewUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    category: 'Creative',
    description: 'Bold colors, artistic lighting, stylish attire.',
    promptModifier: 'creative director headshot, stylish fashion-forward business attire, artistic dramatic lighting, colored gel rim light, dark moody studio background, intense and creative look, 8k resolution',
    iconName: 'Camera',
    colorFrom: 'from-purple-500',
    colorTo: 'to-pink-500',
    previewUrl: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'night-city',
    name: 'Night Cityscape',
    category: 'Creative',
    description: 'Urban evening vibe with colorful city bokeh.',
    promptModifier: 'urban night portrait, wearing leather jacket or smart casual, background of city skyline at night with colorful bokeh lights, cinematic lighting, cool and edgy, 8k',
    iconName: 'Moon',
    colorFrom: 'from-blue-900',
    colorTo: 'to-purple-900',
    previewUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    category: 'Creative',
    description: 'Nostalgic, grainy film look with warm tones and soft focus.',
    promptModifier: 'vintage film photo, 1970s aesthetic, worn film grain, warm sepia tones, soft focus, cinematic lighting, 8k',
    iconName: 'Film',
    colorFrom: 'from-orange-400',
    colorTo: 'to-amber-600',
    previewUrl: 'https://images.unsplash.com/photo-1515516981886-df80e0a5c48f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'Creative',
    description: 'Neon lights, high-tech fashion, futuristic city.',
    promptModifier: 'futuristic cyberpunk portrait, neon lighting, high-tech clothing with glowing elements, dark city background with neon signs (cyan and magenta), cinematic, 8k, synthwave aesthetic',
    iconName: 'Cpu',
    colorFrom: 'from-fuchsia-600',
    colorTo: 'to-cyan-600',
    previewUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'pencil-sketch',
    name: 'Pencil Sketch',
    category: 'Creative',
    description: 'Hand-drawn charcoal and graphite artistic sketch.',
    promptModifier: 'charcoal pencil sketch portrait on textured white paper, hand drawn artistic style, rough graphite strokes, cross-hatching, high contrast shading, monochromatic, detailed fine art',
    iconName: 'PenTool',
    colorFrom: 'from-gray-400',
    colorTo: 'to-slate-600',
    previewUrl: 'https://images.unsplash.com/photo-1596796929944-77dc35c138c1?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'ghibli-anime',
    name: 'Anime World',
    category: 'Creative',
    description: 'Whimsical animation style inspired by Studio Ghibli.',
    promptModifier: 'studio ghibli style anime portrait, hayao miyazaki art style, vibrant watercolor background with fluffy clouds and lush nature, cel shaded, whimsical, emotional, soft lighting, 8k',
    iconName: 'Flower2',
    colorFrom: 'from-sky-400',
    colorTo: 'to-green-400',
    previewUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'oil-painting',
    name: 'Classic Oil',
    category: 'Creative',
    description: 'Textured Renaissance-style oil painting.',
    promptModifier: 'classical oil painting portrait, heavy impasto brushstrokes, canvas texture, rembrandt lighting, renaissance art style, museum quality, rich colors, 8k',
    iconName: 'Brush',
    colorFrom: 'from-amber-700',
    colorTo: 'to-yellow-600',
    previewUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: '3d-render',
    name: '3D Avatar',
    category: 'Creative',
    description: 'Cute 3D animated character style.',
    promptModifier: '3d pixar disney style character portrait, stylized 3d render, cute features, big expressive eyes, soft smooth skin texture, volumetric lighting, octane render, 4k',
    iconName: 'Gamepad2',
    colorFrom: 'from-blue-400',
    colorTo: 'to-pink-400',
    previewUrl: 'https://images.unsplash.com/photo-1633511090164-b43840eaeb60?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    category: 'Creative',
    description: 'Colorful Andy Warhol style pop art.',
    promptModifier: 'pop art style portrait, andy warhol inspired, vibrant contrasting colors (magenta, cyan, yellow), bold screen print texture, graphic and stylized, retro artistic, 8k',
    iconName: 'Palette',
    colorFrom: 'from-yellow-400',
    colorTo: 'to-pink-500',
    previewUrl: 'https://images.unsplash.com/photo-1550928431-ee0ec6db30d3?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'watercolor-splash',
    name: 'Watercolor',
    category: 'Creative',
    description: 'Soft and artistic watercolor painting style.',
    promptModifier: 'watercolor painting portrait, soft pastel colors, artistic splashes and drips on white paper texture, dreamy and ethereal, wet-on-wet technique, fine art, 8k',
    iconName: 'Droplets',
    colorFrom: 'from-cyan-300',
    colorTo: 'to-purple-300',
    previewUrl: 'https://images.unsplash.com/photo-1582201943021-e8e6444cf12d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'marble-statue',
    name: 'Marble Statue',
    category: 'Creative',
    description: 'Classical white marble sculpture look.',
    promptModifier: 'white marble statue bust portrait, classical greek sculpture style, smooth stone texture, museum lighting, monochromatic white and grey, artistic and timeless, 8k',
    iconName: 'User',
    colorFrom: 'from-gray-200',
    colorTo: 'to-slate-400',
    previewUrl: 'https://images.unsplash.com/photo-1549845375-303d865c328e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    category: 'Creative',
    description: 'Retro 8-bit video game character style.',
    promptModifier: 'pixel art portrait, 8-bit video game style, blocky retro graphics, vibrant colors, limited color palette, digital avatar, 4k',
    iconName: 'Grid',
    colorFrom: 'from-green-400',
    colorTo: 'to-blue-400',
    previewUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'noir-detective',
    name: 'Noir Detective',
    category: 'Creative',
    description: 'Moody black and white film noir mystery.',
    promptModifier: 'film noir detective portrait, black and white photography, high contrast dramatic shadows (chiaroscuro), wearing fedora or trench coat, mysterious rainy city background, cinematic vintage style, 8k',
    iconName: 'Search',
    colorFrom: 'from-black',
    colorTo: 'to-gray-800',
    previewUrl: 'https://images.unsplash.com/photo-1616012480717-fd9867059ca0?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'space-explorer',
    name: 'Space Explorer',
    category: 'Creative',
    description: 'Astronaut style in a sci-fi setting.',
    promptModifier: 'astronaut portrait, wearing futuristic space suit and helmet, background of outer space with nebula and stars, cinematic sci-fi lighting, heroic and adventurous, 8k',
    iconName: 'Rocket',
    colorFrom: 'from-indigo-900',
    colorTo: 'to-black',
    previewUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'fantasy-elf',
    name: 'Fantasy Elf',
    category: 'Creative',
    description: 'Ethereal high-fantasy character with nature vibes.',
    promptModifier: 'high fantasy elf portrait, ethereal beauty, slightly pointed ears, wearing nature-inspired armor or robes, background of magical forest with glowing particles, soft magical lighting, 8k',
    iconName: 'Leaf',
    colorFrom: 'from-emerald-400',
    colorTo: 'to-green-600',
    previewUrl: 'https://images.unsplash.com/photo-1598974357801-cbca100e65d3?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'steampunk',
    name: 'Steampunk',
    category: 'Creative',
    description: 'Victorian sci-fi with brass gears and goggles.',
    promptModifier: 'steampunk portrait, victorian fashion with brass gears and goggles, leather accessories, background of steam-powered machinery, sepia tones, detailed and gritty, 8k',
    iconName: 'Settings',
    colorFrom: 'from-amber-800',
    colorTo: 'to-yellow-700',
    previewUrl: 'https://images.unsplash.com/photo-1542178243-bc20204b769f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'claymation-style',
    name: 'Claymation',
    category: 'Creative',
    description: 'Stop-motion animation look with plasticine textures.',
    promptModifier: 'claymation style character portrait, stop-motion plasticine texture, aardman animation style, soft rounded features, handmade look, playful and quirky, studio lighting, 4k',
    iconName: 'Hexagon',
    colorFrom: 'from-orange-400',
    colorTo: 'to-yellow-500',
    previewUrl: 'https://images.unsplash.com/photo-1515966097209-ec48f3216298?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'low-poly-art',
    name: 'Low Poly',
    category: 'Creative',
    description: 'Geometric low-polygon digital art style.',
    promptModifier: 'low poly art portrait, geometric polygon mesh style, sharp facets, minimalist digital art, vibrant flat shading, abstract and modern, 4k resolution',
    iconName: 'Grid',
    colorFrom: 'from-blue-500',
    colorTo: 'to-cyan-600',
    previewUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- GROUP PHOTOS (18 Styles) ---
  {
    id: 'corporate-team',
    name: 'Corporate Team',
    category: 'Group Photos',
    description: 'Professional group photo for company websites.',
    promptModifier: 'corporate team group photo, professional business people standing together confidently, wearing modern business suits, bright modern office background, soft balanced studio lighting, 8k, team portrait',
    iconName: 'Briefcase',
    colorFrom: 'from-slate-600',
    colorTo: 'to-blue-800',
    previewUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'startup-squad',
    name: 'Startup Squad',
    category: 'Group Photos',
    description: 'Casual, energetic team in a modern workspace.',
    promptModifier: 'startup team group photo, young professionals wearing smart casual, energetic and happy, modern co-working space background with glass and whiteboards, bright natural light, 8k',
    iconName: 'Rocket',
    colorFrom: 'from-purple-500',
    colorTo: 'to-pink-500',
    previewUrl: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'medical-team',
    name: 'Medical Team',
    category: 'Group Photos',
    description: 'Doctors and nurses in a hospital setting.',
    promptModifier: 'medical team group photo, doctors and nurses wearing white coats and scrubs, hospital corridor background, professional and trustworthy, bright clean lighting, 8k',
    iconName: 'Stethoscope',
    colorFrom: 'from-teal-500',
    colorTo: 'to-cyan-600',
    previewUrl: 'https://images.unsplash.com/photo-1576091160550-2187d80aeff2?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'construction-crew',
    name: 'Construction Crew',
    category: 'Group Photos',
    description: 'Rugged team on a construction site.',
    promptModifier: 'construction team group photo, wearing safety vests and hard hats, background of a building site with cranes, rugged and strong, sunset lighting, 8k',
    iconName: 'HardHat',
    colorFrom: 'from-orange-500',
    colorTo: 'to-yellow-600',
    previewUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'sports-team',
    name: 'Sports Team',
    category: 'Group Photos',
    description: 'Athletic team in matching uniforms.',
    promptModifier: 'sports team group photo, athletes wearing matching team uniforms, stadium or field background, energetic and fit, dramatic sports lighting, 8k',
    iconName: 'Trophy',
    colorFrom: 'from-blue-600',
    colorTo: 'to-red-600',
    previewUrl: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'rock-band',
    name: 'Rock Band',
    category: 'Group Photos',
    description: 'Edgy band promo photo with instruments.',
    promptModifier: 'rock band group photo, musicians with instruments, edgy rock fashion, leather jackets, brick wall or stage background, moody dramatic lighting, cool attitude, 8k',
    iconName: 'Music',
    colorFrom: 'from-slate-800',
    colorTo: 'to-black',
    previewUrl: 'https://images.unsplash.com/photo-1493225255756-d9584f8606e9?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'studio-family',
    name: 'Family Portrait',
    category: 'Group Photos',
    description: 'Classic family photo in a studio.',
    promptModifier: 'family studio portrait, group of family members wearing coordinated clothing (white shirts and jeans), clean white or grey background, happy smiles, soft studio lighting, 8k',
    iconName: 'Home',
    colorFrom: 'from-amber-100',
    colorTo: 'to-amber-300',
    previewUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'outdoor-friends',
    name: 'Outdoor Friends',
    category: 'Group Photos',
    description: 'Casual group of friends in nature.',
    promptModifier: 'group of friends hanging out outdoors, casual clothing, park or nature background with trees, laughing and candid, natural sunlight, happy vibe, 8k',
    iconName: 'Users',
    colorFrom: 'from-green-400',
    colorTo: 'to-yellow-400',
    previewUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'wedding-party',
    name: 'Wedding Party',
    category: 'Group Photos',
    description: 'Bridesmaids and Groomsmen formal photo.',
    promptModifier: 'wedding party group photo, bridesmaids and groomsmen in formal wedding attire, outdoor garden or church background, elegant and celebratory, soft romantic lighting, 8k',
    iconName: 'Heart',
    colorFrom: 'from-pink-300',
    colorTo: 'to-rose-400',
    previewUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'grad-class',
    name: 'Class of 2024',
    category: 'Group Photos',
    description: 'Students in graduation gowns tossing caps.',
    promptModifier: 'graduation group photo, students wearing caps and gowns, university campus background, celebrating and happy, tossing caps (optional), bright daylight, 8k',
    iconName: 'GraduationCap',
    colorFrom: 'from-indigo-600',
    colorTo: 'to-blue-700',
    previewUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'adventure-club',
    name: 'Adventure Club',
    category: 'Group Photos',
    description: 'Hikers on a mountain trail.',
    promptModifier: 'hiking group photo, people wearing outdoor adventure gear with backpacks, mountain trail background with scenic view, adventurous and active, natural sunlight, 8k',
    iconName: 'MapPin',
    colorFrom: 'from-green-600',
    colorTo: 'to-emerald-700',
    previewUrl: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'beach-squad',
    name: 'Beach Squad',
    category: 'Group Photos',
    description: 'Summer fun group photo on the beach.',
    promptModifier: 'beach group photo, friends wearing summer beachwear, ocean and sand background, blue sky, sunny and vibrant, vacation vibe, 8k',
    iconName: 'Waves',
    colorFrom: 'from-cyan-400',
    colorTo: 'to-blue-500',
    previewUrl: 'https://images.unsplash.com/photo-1471922694854-ff1b63b20054?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'holiday-family',
    name: 'Holiday Family',
    category: 'Group Photos',
    description: 'Family in matching holiday sweaters.',
    promptModifier: 'christmas family group photo, wearing matching holiday sweaters, cozy living room background with christmas tree and fireplace, warm festive lighting, happy togetherness, 8k',
    iconName: 'Gift',
    colorFrom: 'from-red-600',
    colorTo: 'to-green-700',
    previewUrl: 'https://images.unsplash.com/photo-1576016770956-debb63d92058?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'yoga-class',
    name: 'Yoga Group',
    category: 'Group Photos',
    description: 'Peaceful yoga class in a studio.',
    promptModifier: 'yoga class group photo, people in yoga attire sitting in lotus pose, bright airy studio background with plants, peaceful and zen, soft lighting, 8k',
    iconName: 'Leaf',
    colorFrom: 'from-emerald-300',
    colorTo: 'to-green-400',
    previewUrl: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'kitchen-brigade',
    name: 'Kitchen Brigade',
    category: 'Group Photos',
    description: 'Chefs and cooks in a professional kitchen.',
    promptModifier: 'chef team group photo, chefs wearing white jackets and hats, professional stainless steel kitchen background, confident and skilled, bright lighting, 8k',
    iconName: 'ChefHat',
    colorFrom: 'from-slate-200',
    colorTo: 'to-slate-400',
    previewUrl: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'military-squad',
    name: 'Military Squad',
    category: 'Group Photos',
    description: 'Soldiers in uniform standing in formation.',
    promptModifier: 'military squad group photo, soldiers wearing camouflage uniforms, standing in formation, military base or field background, disciplined and serious, dramatic lighting, 8k',
    iconName: 'Shield',
    colorFrom: 'from-green-800',
    colorTo: 'to-stone-800',
    previewUrl: 'https://images.unsplash.com/photo-1542359218-e3624f2b9347?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-breaking-news',
    name: 'Breaking News',
    category: 'Social Media Status',
    description: 'Breaking News TV broadcast overlay.',
    promptModifier: 'breaking news television broadcast style, text overlays "BREAKING NEWS", professional news anchor studio background, dramatic urgent lighting, 8k',
    iconName: 'Megaphone',
    colorFrom: 'from-red-600',
    colorTo: 'to-red-800',
    previewUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-influencer',
    name: 'Influencer Vibe',
    category: 'Social Media Status',
    description: 'Trendy, aesthetic influencer lifestyle shot.',
    promptModifier: 'social media influencer portrait, stylish trendy clothing, aesthetic cafe or street background, bright ring light effect, engaging smile, viral content style, 8k',
    iconName: 'Heart',
    colorFrom: 'from-pink-500',
    colorTo: 'to-purple-500',
    previewUrl: 'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-podcast',
    name: 'Podcast Host',
    category: 'Social Media Status',
    description: 'Professional podcast recording setup.',
    promptModifier: 'podcast host portrait, wearing headphones, sitting at a microphone, soundproof studio background with neon accent lights, engaging and talkative expression, 8k',
    iconName: 'Mic2',
    colorFrom: 'from-blue-600',
    colorTo: 'to-indigo-800',
    previewUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-fitness',
    name: 'Fitness Guru',
    category: 'Social Media Status',
    description: 'High energy fitness influencer look.',
    promptModifier: 'fitness influencer portrait, wearing gym shark style sportswear, holding protein shaker or weights, modern gym background, energetic and fit, bright lighting, 8k',
    iconName: 'Dumbbell',
    colorFrom: 'from-emerald-500',
    colorTo: 'to-teal-600',
    previewUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-travel',
    name: 'Wanderlust',
    category: 'Social Media Status',
    description: 'Dreamy travel vlog aesthetic.',
    promptModifier: 'travel vlogger portrait, holding a camera or gopro, background of scenic mountain or beach, golden hour lighting, adventurous and free, wanderlust vibe, 8k',
    iconName: 'Plane',
    colorFrom: 'from-orange-400',
    colorTo: 'to-yellow-500',
    previewUrl: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-foodie',
    name: 'Food Vlogger',
    category: 'Social Media Status',
    description: 'Holding delicious food, restaurant vibe.',
    promptModifier: 'food vlogger portrait, holding a delicious gourmet dish, background of trendy restaurant, warm appetizing lighting, happy eating expression, 8k',
    iconName: 'ChefHat',
    colorFrom: 'from-red-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-gamer',
    name: 'Pro Gamer',
    category: 'Social Media Status',
    description: 'RGB lighting, gaming headset, streamer vibe.',
    promptModifier: 'pro gamer streamer portrait, wearing gaming headset, background of gaming setup with RGB led lights, intense focus or happy win expression, cyber style, 8k',
    iconName: 'Gamepad2',
    colorFrom: 'from-purple-600',
    colorTo: 'to-blue-600',
    previewUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-tech-review',
    name: 'Tech Reviewer',
    category: 'Social Media Status',
    description: 'Holding latest gadgets, clean studio.',
    promptModifier: 'tech reviewer portrait, holding a modern smartphone or gadget, clean white or tech studio background, smart and analytical expression, 8k',
    iconName: 'Smartphone',
    colorFrom: 'from-gray-700',
    colorTo: 'to-black',
    previewUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-motivation',
    name: 'Motivator',
    category: 'Social Media Status',
    description: 'Inspirational speaker look with stage lighting.',
    promptModifier: 'motivational speaker portrait, standing on stage with microphone, spotlight background, confident and inspiring pose, ted talk vibe, 8k',
    iconName: 'Mic2',
    colorFrom: 'from-yellow-600',
    colorTo: 'to-orange-700',
    previewUrl: 'https://images.unsplash.com/photo-1475721027767-p74302942437?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-artist',
    name: 'Digital Artist',
    category: 'Social Media Status',
    description: 'Creative workspace with tablet and art.',
    promptModifier: 'digital artist portrait, holding a drawing tablet, background of art studio with colorful artwork, creative lighting, artistic vibe, 8k',
    iconName: 'PenTool',
    colorFrom: 'from-pink-500',
    colorTo: 'to-cyan-500',
    previewUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-musician',
    name: 'Indie Musician',
    category: 'Social Media Status',
    description: 'Holding guitar, acoustic session vibe.',
    promptModifier: 'indie musician portrait, holding acoustic guitar, background of cozy home studio or coffee shop, soft warm lighting, artistic and soulful, 8k',
    iconName: 'Music',
    colorFrom: 'from-amber-600',
    colorTo: 'to-brown-700',
    previewUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-comedy',
    name: 'Stand-up Comic',
    category: 'Social Media Status',
    description: 'Brick wall background, microphone, laughing.',
    promptModifier: 'stand-up comedian portrait, holding microphone, background of brick wall comedy club, spotlight, laughing or telling a joke, fun energetic vibe, 8k',
    iconName: 'Smile',
    colorFrom: 'from-purple-700',
    colorTo: 'to-indigo-900',
    previewUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-crypto',
    name: 'Crypto Bro',
    category: 'Social Media Status',
    description: 'Charts in background, laser eyes optional.',
    promptModifier: 'crypto trader portrait, background of trading charts and green candles, confident success vibe, laser eyes effect optional, modern financial look, 8k',
    iconName: 'TrendingUp',
    colorFrom: 'from-green-500',
    colorTo: 'to-emerald-700',
    previewUrl: 'https://images.unsplash.com/photo-1611974765270-ca12586343bb?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-fashion',
    name: 'Street Style',
    category: 'Social Media Status',
    description: 'Urban fashion, OOTD look.',
    promptModifier: 'street style fashion portrait, wearing trendy urban outfit, background of city street or graffiti wall, natural daylight, stylish and cool, 8k',
    iconName: 'Shirt',
    colorFrom: 'from-fuchsia-500',
    colorTo: 'to-pink-600',
    previewUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-pet',
    name: 'Pet Lover',
    category: 'Social Media Status',
    description: 'Holding a cute dog or cat.',
    promptModifier: 'pet lover portrait, holding a cute dog or cat, soft home background, bright happy lighting, warm and loving expression, 8k',
    iconName: 'Heart',
    colorFrom: 'from-orange-400',
    colorTo: 'to-yellow-400',
    previewUrl: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-party',
    name: 'Club Promoter',
    category: 'Social Media Status',
    description: 'Nightlife vibes, neon and drinks.',
    promptModifier: 'nightlife party portrait, holding a drink, background of nightclub with neon lights, energetic and fun, flash photography style, 8k',
    iconName: 'GlassWater',
    colorFrom: 'from-purple-600',
    colorTo: 'to-pink-600',
    previewUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-spiritual',
    name: 'Spiritual Guru',
    category: 'Social Media Status',
    description: 'Peaceful meditation vibe, nature background.',
    promptModifier: 'spiritual meditation portrait, sitting in lotus pose, background of peaceful nature or temple, soft ethereal lighting, calm and enlightened expression, 8k',
    iconName: 'Sun',
    colorFrom: 'from-yellow-200',
    colorTo: 'to-orange-200',
    previewUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'social-festive',
    name: 'Festival Vibes',
    category: 'Social Media Status',
    description: 'Music festival look with glitter and boho style.',
    promptModifier: 'music festival portrait, wearing boho festival outfit with glitter, background of festival crowd and flags, sunset lighting, free spirit vibe, 8k',
    iconName: 'Music',
    colorFrom: 'from-pink-500',
    colorTo: 'to-orange-500',
    previewUrl: 'https://images.unsplash.com/photo-1533174072545-e8d4aa97d890?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },

  // --- PROFILE POSES (12 Styles) ---
  {
    id: 'profile-studio-sitting',
    name: 'Studio Sitting',
    category: 'Profile Poses',
    description: 'Classic professional sitting pose on a stool.',
    promptModifier: 'full body sitting pose portrait, sitting elegantly on a stool, wearing professional business attire, studio grey background, soft lighting, confident posture, hands resting on lap, 8k',
    iconName: 'Armchair',
    colorFrom: 'from-slate-500',
    colorTo: 'to-slate-700',
    previewUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isPremium: false // FREE
  },
  {
    id: 'profile-armchair',
    name: 'Executive Armchair',
    category: 'Profile Poses',
    description: 'Authoritative pose sitting in a leather armchair.',
    promptModifier: 'executive portrait sitting in a leather armchair, wearing tailored suit, background of office library, confident relaxed posture, warm lighting, authoritative vibe, 8k',
    iconName: 'Armchair',
    colorFrom: 'from-amber-700',
    colorTo: 'to-orange-900',
    previewUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-standing-arms-crossed',
    name: 'Standing Confident',
    category: 'Profile Poses',
    description: 'Standing pose with arms crossed, projecting confidence.',
    promptModifier: 'professional standing portrait, arms crossed confidently, wearing business casual or suit, blurred office background, strong posture, friendly smile, bright lighting, 8k',
    iconName: 'MoveVertical',
    colorFrom: 'from-blue-600',
    colorTo: 'to-indigo-700',
    previewUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-leaning-wall',
    name: 'Leaning Casual',
    category: 'Profile Poses',
    description: 'Relaxed standing pose leaning against a wall.',
    promptModifier: 'casual portrait leaning against a wall, wearing stylish casual clothes, urban brick or textured wall background, relaxed and approachable, natural lighting, 8k',
    iconName: 'MoveVertical',
    colorFrom: 'from-slate-600',
    colorTo: 'to-gray-700',
    previewUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-desk-sitting',
    name: 'Desk Work',
    category: 'Profile Poses',
    description: 'Sitting at a desk, engaged in work.',
    promptModifier: 'professional portrait sitting at a desk, laptop open, wearing smart business attire, modern office background, engaged and focused expression, bright workspace lighting, 8k',
    iconName: 'Laptop',
    colorFrom: 'from-cyan-600',
    colorTo: 'to-blue-600',
    previewUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-side-profile',
    name: 'Side Profile',
    category: 'Profile Poses',
    description: 'Artistic side view profile shot.',
    promptModifier: 'side profile portrait, facing left or right, dramatic lighting highlighting facial features, neutral studio background, artistic and contemplative, 8k',
    iconName: 'User',
    colorFrom: 'from-purple-600',
    colorTo: 'to-pink-600',
    previewUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-walking',
    name: 'Walking Shot',
    category: 'Profile Poses',
    description: 'Dynamic shot of walking towards the camera.',
    promptModifier: 'dynamic portrait walking towards camera, wearing stylish street fashion, blurred city street background, movement blur in background, confident stride, natural daylight, 8k',
    iconName: 'Footprints',
    colorFrom: 'from-emerald-600',
    colorTo: 'to-teal-600',
    previewUrl: 'https://images.unsplash.com/photo-1485230405346-71acb9518d9c?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-stairs-sitting',
    name: 'Stairs Sitting',
    category: 'Profile Poses',
    description: 'Casual pose sitting on steps or stairs.',
    promptModifier: 'casual portrait sitting on steps or stairs, wearing jeans and casual top, outdoor urban or park setting, relaxed posture, hands on knees, natural lighting, 8k',
    iconName: 'MoveVertical',
    colorFrom: 'from-orange-500',
    colorTo: 'to-red-600',
    previewUrl: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-hands-pockets',
    name: 'Hands in Pockets',
    category: 'Profile Poses',
    description: 'Standing with hands in pockets, cool vibe.',
    promptModifier: 'standing portrait with hands in pockets, wearing smart casual or suit, neutral background, cool and relaxed demeanor, fashion lighting, 8k',
    iconName: 'User',
    colorFrom: 'from-indigo-600',
    colorTo: 'to-blue-800',
    previewUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-looking-away',
    name: 'Looking Away',
    category: 'Profile Poses',
    description: 'Candid style looking off-camera.',
    promptModifier: 'candid portrait looking away from camera, laughing or smiling naturally, blurred lifestyle background, soft natural light, authentic and unposed feel, 8k',
    iconName: 'Eye',
    colorFrom: 'from-rose-400',
    colorTo: 'to-pink-500',
    previewUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-podium',
    name: 'Podium Speaker',
    category: 'Profile Poses',
    description: 'Standing behind a podium, giving a speech.',
    promptModifier: 'public speaker portrait standing behind a podium, wearing suit, background of conference hall or stage curtains, speaking gesture, authoritative and engaging, 8k',
    iconName: 'Mic2',
    colorFrom: 'from-blue-700',
    colorTo: 'to-slate-800',
    previewUrl: 'https://images.unsplash.com/photo-1544168835-84dc0ae36629?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  },
  {
    id: 'profile-cafeteria',
    name: 'Cafe Seating',
    category: 'Profile Poses',
    description: 'Sitting at a cafe table with a drink.',
    promptModifier: 'portrait sitting at a cafe table, coffee cup on table, wearing casual chic, blurred cafe interior background, warm ambient lighting, relaxed conversation vibe, 8k',
    iconName: 'Coffee',
    colorFrom: 'from-amber-600',
    colorTo: 'to-brown-700',
    previewUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    isPremium: true
  }
];