
import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { GeneratedImage, StyleOption } from '../types';
import { Download, RefreshCw, Wand2, Loader2, Sparkles, Aperture, Circle, Printer, X, Check, User, Grid3X3, Scissors, Share2, Linkedin, Facebook, Instagram, Twitter, FileText, MessageSquare, SlidersHorizontal, Activity, Droplets, SunMedium } from 'lucide-react';
import { ToastType } from './Toast';

interface ResultDisplayProps {
  originalImage: string;
  generatedImage: GeneratedImage;
  selectedStyle: StyleOption;
  onReset: () => void;
  onUpscale: () => Promise<void>;
  isPremium?: boolean;
  onShowToast?: (msg: string, type: ToastType) => void;
}

const FILTERS = [
  { id: 'original', name: 'Original', value: 'none' },
  { id: 'professional', name: 'Professional', value: 'contrast(110%) brightness(105%) saturate(105%)' },
  { id: 'matte', name: 'Matte', value: 'contrast(90%) brightness(110%) saturate(90%)' },
  { id: 'bw', name: 'B&W', value: 'grayscale(100%) contrast(110%)' },
  { id: 'warm', name: 'Warm', value: 'sepia(20%) saturate(120%) brightness(105%)' },
  { id: 'cool', name: 'Cool', value: 'saturate(110%) hue-rotate(10deg) brightness(105%)' },
  { id: 'vivid', name: 'Vivid', value: 'saturate(130%) contrast(110%)' },
  { id: 'vintage', name: 'Vintage', value: 'sepia(40%) contrast(110%) brightness(90%) saturate(80%)' },
  { id: 'dramatic', name: 'Dramatic', value: 'contrast(130%) saturate(110%) brightness(95%)' },
  { id: 'soft', name: 'Soft', value: 'brightness(105%) contrast(95%) sepia(5%)' },
];

// 300 DPI Pixel Conversions (approx)
const PASSPORT_CONFIGS = {
  48: {
    label: "Stamp (48)",
    desc: "2.5cm x 2.5cm",
    photoW: 295,
    photoH: 295,
    cols: 6,
    rows: 8,
    orientation: 'portrait' as const
  },
  30: { 
    label: "Standard (30)",
    desc: "3.5cm x 4.5cm",
    photoW: 413, 
    photoH: 531, 
    cols: 5, 
    rows: 6,
    orientation: 'portrait' as const
  },
  18: { 
    label: "Medium (18)", 
    desc: "4.5cm x 6cm",
    photoW: 531, 
    photoH: 708, 
    cols: 6, 
    rows: 3,
    orientation: 'landscape' as const
  },
  15: {
    label: "Visa (15)",
    desc: "2x2 inch (5x5cm)",
    photoW: 600,
    photoH: 600,
    cols: 3,
    rows: 5,
    orientation: 'portrait' as const
  },
  12: { 
    label: "Large (12)", 
    desc: "5cm x 7cm",
    photoW: 590, 
    photoH: 826, 
    cols: 3, 
    rows: 4,
    orientation: 'portrait' as const
  }
};

type PassportCount = 48 | 30 | 18 | 15 | 12;

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ originalImage, generatedImage, selectedStyle, onReset, onUpscale, isPremium = false, onShowToast }) => {
  const [activeFilter, setActiveFilter] = useState(FILTERS[0]);
  const [blurAmount, setBlurAmount] = useState(0);
  const [vignetteAmount, setVignetteAmount] = useState(0);
  
  // Advanced Adjustments
  const [sharpness, setSharpness] = useState(0); // 0-100
  const [saturation, setSaturation] = useState(100); // 0-200%
  const [contrast, setContrast] = useState(100); // 0-200%

  const [isDownloading, setIsDownloading] = useState(false);
  const [isUpscaling, setIsUpscaling] = useState(false);
  const [isUpscaled, setIsUpscaled] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [shareText, setShareText] = useState("Check out my new professional headshot generated by KrishnaLense.AI! 📸✨ #AIHeadshot #Professional #KrishnaLenseAI");
  
  // Passport Mode State
  const [showPassportModal, setShowPassportModal] = useState(false);
  const [passportUrl, setPassportUrl] = useState<string | null>(null);
  const [singlePassportUrl, setSinglePassportUrl] = useState<string | null>(null);
  const [isGeneratingPassport, setIsGeneratingPassport] = useState(false);
  const [passportCount, setPassportCount] = useState<PassportCount>(30);

  // Store the processed source canvas to avoid re-filtering
  const [processedSourceCanvas, setProcessedSourceCanvas] = useState<HTMLCanvasElement | null>(null);

  // Reset adjustments when image changes
  useEffect(() => {
    setProcessedSourceCanvas(null);
  }, [activeFilter, blurAmount, vignetteAmount, sharpness, saturation, contrast]);

  // Construct CSS filter string for preview
  const getPreviewStyle = () => {
    const filters: string[] = [];
    
    // 1. Preset Filter (e.g., B&W, Warm)
    if (activeFilter.value !== 'none') {
      filters.push(activeFilter.value);
    }
    
    // 2. Manual Adjustments
    if (saturation !== 100) filters.push(`saturate(${saturation}%)`);
    if (contrast !== 100) filters.push(`contrast(${contrast}%)`);
    
    // 3. Sharpness (via SVG Filter)
    if (sharpness > 0) filters.push(`url(#sharpness-filter)`);

    return { filter: filters.join(' ') };
  };

  // Helper: Apply Pixel-level sharpening for Canvas (Download)
  const applySharpenToCanvas = (ctx: CanvasRenderingContext2D, width: number, height: number, amount: number) => {
    if (amount <= 0) return;
    
    const imgData = ctx.getImageData(0, 0, width, height);
    const px = imgData.data;
    const w = width;
    const h = height;
    
    // We'll process into a copy to avoid reading modified pixels
    const copy = new Uint8ClampedArray(px);
    
    // Simple kernel weights based on amount (0-100 mapped to 0-1 range roughly)
    const intensity = amount / 100; // 0.0 to 1.0
    // Convolution Logic:
    // val = original + intensity * (4*original - up - down - left - right)
    
    for (let y = 1; y < h - 1; y++) {
      for (let x = 1; x < w - 1; x++) {
        const idx = (y * w + x) * 4;
        
        // RGB channels
        for (let c = 0; c < 3; c++) {
          const center = copy[idx + c];
          const up = copy[idx + c - w * 4];
          const down = copy[idx + c + w * 4];
          const left = copy[idx + c - 4];
          const right = copy[idx + c + 4];
          
          // High pass
          const delta = (4 * center) - up - down - left - right;
          
          // Apply
          px[idx + c] = Math.min(255, Math.max(0, center + (delta * intensity)));
        }
        // Alpha (idx+3) remains unchanged
      }
    }
    
    ctx.putImageData(imgData, 0, 0);
  };

  const getProcessedImageCanvas = async (): Promise<HTMLCanvasElement> => {
    const img = new Image();
    img.crossOrigin = "anonymous"; 
    img.src = generatedImage.url;

    await new Promise((resolve, reject) => {
      img.onload = resolve;
      img.onerror = reject;
    });

    const width = img.naturalWidth;
    const height = img.naturalHeight;

    // 1. Base Composition Canvas
    const compCanvas = document.createElement('canvas');
    compCanvas.width = width;
    compCanvas.height = height;
    const compCtx = compCanvas.getContext('2d');
    
    if (!compCtx) throw new Error("Could not get canvas context");

    // Draw base
    compCtx.drawImage(img, 0, 0);

    // 2. Apply Sharpness (Pixel Manipulation)
    if (sharpness > 0) {
       applySharpenToCanvas(compCtx, width, height, sharpness);
    }

    // 3. Apply Blur Overlay (Background Blur)
    if (blurAmount > 0) {
      const blurCanvas = document.createElement('canvas');
      blurCanvas.width = width;
      blurCanvas.height = height;
      const blurCtx = blurCanvas.getContext('2d');
      
      if (blurCtx) {
        const scaleFactor = Math.max(1, width / 1000);
        const scaledBlur = blurAmount * 2 * scaleFactor;

        blurCtx.filter = `blur(${scaledBlur}px)`;
        blurCtx.drawImage(compCanvas, 0, 0); // Blur the potentially sharpened image
        blurCtx.filter = 'none'; 

        // Focus Mask
        blurCtx.globalCompositeOperation = 'destination-out';
        const gradient = blurCtx.createRadialGradient(
          width / 2, height / 2, width * 0.15, 
          width / 2, height / 2, width * 0.65
        );
        gradient.addColorStop(0, 'rgba(0,0,0,1)'); 
        gradient.addColorStop(1, 'rgba(0,0,0,0)'); 
        
        blurCtx.fillStyle = gradient;
        blurCtx.fillRect(0, 0, width, height);

        compCtx.drawImage(blurCanvas, 0, 0);
      }
    }

    // 4. Apply Vignette
    if (vignetteAmount > 0) {
      const maxDim = Math.max(width, height);
      const vGradient = compCtx.createRadialGradient(
        width / 2, height / 2, width * 0.3, 
        width / 2, height / 2, maxDim * 0.8
      );
      const vOpacity = (vignetteAmount / 10) * 0.8;
      
      vGradient.addColorStop(0, 'rgba(0,0,0,0)');
      vGradient.addColorStop(1, `rgba(0,0,0,${vOpacity})`);
      
      compCtx.fillStyle = vGradient;
      compCtx.fillRect(0, 0, width, height);
    }

    // 5. Apply Color Filters (Presets + Manual Saturation/Contrast)
    const finalCanvas = document.createElement('canvas');
    finalCanvas.width = width;
    finalCanvas.height = height;
    const finalCtx = finalCanvas.getContext('2d');
    
    if (!finalCtx) throw new Error("Could not get final canvas context");

    // Combine preset filters with manual adjustments
    // If activeFilter is 'none', we just use manual. Otherwise append.
    const preset = activeFilter.value === 'none' ? '' : activeFilter.value;
    finalCtx.filter = `${preset} saturate(${saturation}%) contrast(${contrast}%)`.trim();
    
    finalCtx.drawImage(compCanvas, 0, 0);
    finalCtx.filter = 'none'; // Reset filter before drawing watermark

    // 6. Apply Watermark (If Not Premium)
    if (!isPremium) {
      finalCtx.save();
      
      // Calculate Font Sizes relative to image width
      const mainFontSize = Math.floor(width * 0.05); 
      const subFontSize = Math.floor(width * 0.025);
      const padding = Math.floor(width * 0.03);

      finalCtx.textAlign = "left";
      finalCtx.textBaseline = "bottom";
      
      // Position: Bottom Left with Padding
      const x = padding;
      const y = height - padding;

      // --- Text 1: KrishnaLense.AI ---
      finalCtx.font = `900 ${mainFontSize}px Inter, sans-serif`;
      
      // Create Brand Gradient (Blue-400 to Purple-400)
      const gradient = finalCtx.createLinearGradient(x, 0, x + (mainFontSize * 8), 0);
      gradient.addColorStop(0, '#60a5fa');
      gradient.addColorStop(0.5, '#c084fc');
      gradient.addColorStop(1, '#60a5fa');

      // Shadow for Visibility
      finalCtx.shadowColor = "rgba(0,0,0,0.8)";
      finalCtx.shadowBlur = 6;
      finalCtx.shadowOffsetX = 2;
      finalCtx.shadowOffsetY = 2;

      // Draw Main Text
      finalCtx.fillStyle = gradient;
      finalCtx.fillText("KrishnaLense.AI", x, y - subFontSize - (mainFontSize * 0.3));

      // --- Text 2: By Dr. Krishna Karoo ---
      finalCtx.font = `700 ${subFontSize}px Inter, sans-serif`;
      finalCtx.fillStyle = "#94a3b8"; // Slate-400
      finalCtx.shadowBlur = 4; 
      
      finalCtx.fillText("By Dr. Krishna Karoo", x, y);
      
      finalCtx.restore();
    }
    
    return finalCanvas;
  };
  
  const handleDownload = async () => {
    if (!generatedImage.url) return;
    setIsDownloading(true);

    try {
      const finalCanvas = await getProcessedImageCanvas();
      const link = document.createElement('a');
      link.href = finalCanvas.toDataURL('image/png');
      link.download = `pro-headshot-${selectedStyle.id}-${activeFilter.id}-${Date.now()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      onShowToast?.("Image Downloaded!", 'success');
    } catch (error) {
      console.error("Error downloading image:", error);
      onShowToast?.("Download failed. Please try again.", 'error');
    } finally {
      setIsDownloading(false);
    }
  };

  const generatePassportSheet = async (sourceCanvas: HTMLCanvasElement, count: PassportCount) => {
    const config = PASSPORT_CONFIGS[count];
    
    const photoCanvas = document.createElement('canvas');
    photoCanvas.width = config.photoW;
    photoCanvas.height = config.photoH;
    const pCtx = photoCanvas.getContext('2d');
    if (!pCtx) throw new Error("Ctx error");

    const sourceRatio = sourceCanvas.width / sourceCanvas.height;
    const targetRatio = config.photoW / config.photoH;
    
    let sWidth, sHeight, sX, sY;

    if (sourceRatio > targetRatio) {
      sHeight = sourceCanvas.height;
      sWidth = sHeight * targetRatio;
      sX = (sourceCanvas.width - sWidth) / 2;
      sY = 0;
    } else {
      sWidth = sourceCanvas.width;
      sHeight = sWidth / targetRatio;
      sX = 0;
      sY = (sourceCanvas.height - sHeight) / 2;
    }

    pCtx.drawImage(sourceCanvas, sX, sY, sWidth, sHeight, 0, 0, config.photoW, config.photoH);
    // Use quality 1.0 for max fidelity
    setSinglePassportUrl(photoCanvas.toDataURL('image/jpeg', 1.0));

    const sheetCanvas = document.createElement('canvas');
    const A4_SHORT = 2480;
    const A4_LONG = 3508;
    
    if (config.orientation === 'portrait') {
      sheetCanvas.width = A4_SHORT;
      sheetCanvas.height = A4_LONG;
    } else {
      sheetCanvas.width = A4_LONG;
      sheetCanvas.height = A4_SHORT;
    }

    const sCtx = sheetCanvas.getContext('2d');
    if (!sCtx) throw new Error("Sheet ctx error");

    sCtx.fillStyle = '#ffffff';
    sCtx.fillRect(0, 0, sheetCanvas.width, sheetCanvas.height);

    const GAP = 30; 
    const gridW = config.cols * config.photoW + (config.cols - 1) * GAP;
    const gridH = config.rows * config.photoH + (config.rows - 1) * GAP;
    
    const startX = (sheetCanvas.width - gridW) / 2;
    const startY = (sheetCanvas.height - gridH) / 2;

    for (let r = 0; r < config.rows; r++) {
      for (let c = 0; c < config.cols; c++) {
        const x = startX + c * (config.photoW + GAP);
        const y = startY + r * (config.photoH + GAP);
        
        sCtx.drawImage(photoCanvas, x, y);
        sCtx.strokeStyle = '#cbd5e1';
        sCtx.lineWidth = 1;
        sCtx.strokeRect(x, y, config.photoW, config.photoH);
      }
    }

    sCtx.font = "bold 40px Inter, sans-serif";
    sCtx.fillStyle = "#e2e8f0";
    sCtx.textAlign = "center";
    const textX = sheetCanvas.width / 2;
    const textY = sheetCanvas.height - 60;
    sCtx.fillText(`KrishnaLense.AI • ${config.desc} • ${count} Photos`, textX, textY);

    // Use quality 1.0 for print
    return sheetCanvas.toDataURL('image/jpeg', 1.0);
  };

  const handlePassportSheet = async () => {
    if (isGeneratingPassport) return;
    setIsGeneratingPassport(true);
    await new Promise(resolve => setTimeout(resolve, 100));

    try {
      let source = processedSourceCanvas;
      if (!source) {
        source = await getProcessedImageCanvas();
        setProcessedSourceCanvas(source);
      }

      const currentCount = passportCount || 30;
      setPassportCount(currentCount);
      const sheetUrl = await generatePassportSheet(source, currentCount);
      setPassportUrl(sheetUrl);
      setShowPassportModal(true);

    } catch (err: any) {
      console.error(err);
      onShowToast?.("Failed to generate passport sheet.", 'error');
    } finally {
      setIsGeneratingPassport(false);
    }
  };

  const handlePassportCountChange = async (count: PassportCount) => {
    setPassportCount(count);
    if (processedSourceCanvas) {
      setIsGeneratingPassport(true);
      await new Promise(resolve => setTimeout(resolve, 10));
      try {
        const sheetUrl = await generatePassportSheet(processedSourceCanvas, count);
        setPassportUrl(sheetUrl);
      } catch (err) {
        console.error(err);
      }
      setIsGeneratingPassport(false);
    }
  };

  const downloadPassportSheet = () => {
    if (!passportUrl) return;
    const link = document.createElement('a');
    link.href = passportUrl;
    link.download = `passport-sheet-${passportCount}photos-${Date.now()}.jpg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    onShowToast?.("Passport Sheet Downloaded!", 'success');
  };

  const downloadSinglePassport = () => {
    if (!singlePassportUrl) return;
    const link = document.createElement('a');
    link.href = singlePassportUrl;
    link.download = `passport-single-${passportCount}size-${Date.now()}.jpg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    onShowToast?.("Single Photo Downloaded!", 'success');
  };
  
  const handlePrint = () => {
    if (!passportUrl) return;
    const config = PASSPORT_CONFIGS[passportCount];
    const isLandscape = config.orientation === 'landscape';
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Print Passport Photos - ${passportCount} copies</title>
            <style>
              @page { size: A4 ${isLandscape ? 'landscape' : 'portrait'}; margin: 0; }
              body { margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #f0f0f0; }
              img { max-width: 100%; height: auto; box-shadow: 0 4px 20px rgba(0,0,0,0.2); }
              @media print {
                body { background: none; display: block; }
                img { width: 100%; height: 100%; box-shadow: none; }
                .no-print { display: none; }
              }
            </style>
          </head>
          <body>
            <img src="${passportUrl}" />
            <script>
              window.onload = () => {
                setTimeout(() => {
                  window.print();
                  window.close();
                }, 500);
              };
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  const handleUpscaleClick = async () => {
    if (isUpscaling || isUpscaled) return;
    setIsUpscaling(true);
    try {
      await onUpscale();
      setIsUpscaled(true);
      setProcessedSourceCanvas(null);
    } catch (error) {
      // Error handled in parent
    } finally {
      setIsUpscaling(false);
    }
  };

  const dataURLtoFile = async (dataUrl: string, filename: string) => {
    const res = await fetch(dataUrl);
    const blob = await res.blob();
    return new File([blob], filename, { type: 'image/png' });
  };

  const handleShare = async (platform?: 'twitter' | 'facebook' | 'linkedin' | 'instagram') => {
    setIsSharing(true);
    const currentShareText = shareText || "Check out my new professional headshot generated by KrishnaLense.AI!";
    const shareUrl = window.location.href;

    try {
      let nativeShareSuccess = false;
      if ((!platform || platform === 'instagram') && navigator.share) {
        try {
            const canvas = await getProcessedImageCanvas();
            const dataUrl = canvas.toDataURL('image/png');
            const file = await dataURLtoFile(dataUrl, 'krishnalense-headshot.png');
            
            await navigator.share({
              title: 'KrishnaLense.AI Headshot',
              text: currentShareText,
              url: shareUrl,
              files: [file]
            });
            nativeShareSuccess = true;
        } catch (e) {
            console.debug("Native share skipped/cancelled");
        }
      }

      if (nativeShareSuccess) {
          setIsSharing(false);
          return;
      }

      let intentUrl = '';
      const encodedText = encodeURIComponent(currentShareText);
      const encodedUrl = encodeURIComponent(shareUrl);

      switch (platform) {
        case 'twitter':
          intentUrl = `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedUrl}`;
          break;
        case 'facebook':
          intentUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}&quote=${encodedText}`;
          break;
        case 'linkedin':
          intentUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`;
          break;
        case 'instagram':
            intentUrl = `https://www.instagram.com/`;
            break;
      }

      if (intentUrl) {
        window.open(intentUrl, '_blank', platform === 'instagram' ? undefined : 'width=600,height=400');
      } else if (!platform) {
          onShowToast?.("Please download the image first to share!", 'info');
      }

    } catch (error) {
      console.error("Share failed:", error);
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto relative">
       {/* SVG Filter for Preview Sharpness */}
       <svg width="0" height="0" className="absolute pointer-events-none">
          <filter id="sharpness-filter">
             {/* 
                Convolution Matrix for Sharpening
                Center (1 + 4k), Neighbors (-k)
                k = sharpness / 100
             */}
             <feConvolveMatrix
               order="3"
               preserveAlpha="true"
               kernelMatrix={`0 ${-sharpness/100} 0 ${-sharpness/100} ${1 + 4*(sharpness/100)} ${-sharpness/100} 0 ${-sharpness/100} 0`}
             />
          </filter>
       </svg>

       {/* Passport Modal */}
       {showPassportModal && passportUrl && document.body && createPortal(
         <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-slate-900/90 backdrop-blur-md">
           <div className="bg-slate-800 border border-slate-700 rounded-3xl max-w-5xl w-full max-h-[95vh] flex flex-col shadow-2xl overflow-hidden animate-fade-in-up">
             <div className="p-6 border-b border-slate-700 flex justify-between items-center bg-slate-800">
               <div>
                 <h3 className="text-xl font-bold text-white">Passport Photo Studio</h3>
                 <p className="text-slate-400 text-sm">Ready for A4 Printing.</p>
               </div>
               <button onClick={() => setShowPassportModal(false)} className="p-2 hover:bg-slate-700 rounded-full text-slate-400 hover:text-white">
                 <X className="w-6 h-6" />
               </button>
             </div>
             
             <div className="flex flex-col md:flex-row h-full overflow-hidden">
                <div className="w-full md:w-80 bg-slate-900 border-r border-slate-700 p-6 flex flex-col gap-6 overflow-y-auto custom-scrollbar">
                   <div>
                     <label className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3 block">Select Layout</label>
                     <div className="grid grid-cols-2 gap-2">
                        {([48, 30, 18, 15, 12] as PassportCount[]).map((key) => {
                           const cfg = PASSPORT_CONFIGS[key];
                           const isActive = passportCount === Number(key);
                           return (
                            <button 
                              key={key}
                              onClick={() => handlePassportCountChange(Number(key) as PassportCount)}
                              className={`p-3 rounded-xl flex flex-col items-center text-center transition-all border
                                ${isActive 
                                  ? 'bg-blue-600 border-blue-500 text-white shadow-lg' 
                                  : 'bg-slate-800 border-slate-700 text-slate-400 hover:bg-slate-700 hover:border-slate-600'
                                }`}
                            >
                              <span className="text-lg font-bold block">{cfg.label.split(' ')[0]}</span>
                              <span className="text-xs opacity-70">{cfg.desc}</span>
                            </button>
                           )
                        })}
                     </div>
                   </div>

                   <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl text-amber-200 text-xs space-y-2">
                      <div className="flex items-center gap-2 font-bold">
                        <Printer className="w-4 h-4" />
                        <span>Printing Instructions</span>
                      </div>
                      <ul className="list-disc list-inside opacity-80 space-y-1 pl-1">
                        <li>Paper Size: <strong>A4</strong></li>
                        <li>Paper Type: <strong>Photo Paper</strong></li>
                        <li>Scale: <strong>100%</strong></li>
                      </ul>
                   </div>

                   <div className="mt-auto space-y-3">
                      {singlePassportUrl && (
                       <button onClick={downloadSinglePassport} className="w-full py-3 rounded-xl font-bold bg-slate-800 text-white hover:bg-slate-700 border border-slate-600 transition-colors shadow-lg flex items-center justify-center gap-2">
                         <User className="w-4 h-4 text-blue-400" />
                         Download Single
                       </button>
                     )}
                     <button onClick={downloadPassportSheet} className="w-full py-3 rounded-xl font-bold bg-slate-700 text-white hover:bg-slate-600 shadow-lg border border-slate-600 flex items-center justify-center gap-2">
                       <Download className="w-4 h-4" />
                       Download A4 Sheet
                     </button>
                     <button onClick={handlePrint} className="w-full py-3 rounded-xl font-bold bg-blue-600 text-white hover:bg-blue-500 shadow-lg shadow-blue-600/20 flex items-center justify-center gap-2">
                       <Printer className="w-4 h-4" />
                       Print Sheet Now
                     </button>
                   </div>
                </div>

                <div className="flex-1 bg-slate-950/50 p-8 flex items-center justify-center overflow-auto relative">
                   {isGeneratingPassport && (
                     <div className="absolute inset-0 flex items-center justify-center bg-slate-900/50 z-10 backdrop-blur-sm">
                       <Loader2 className="w-10 h-10 animate-spin text-blue-500" />
                     </div>
                   )}
                   <div className="relative shadow-2xl border-8 border-white bg-white max-w-full">
                      <img src={passportUrl} alt="Passport Preview" className="max-h-[70vh] object-contain" />
                   </div>
                </div>
             </div>
           </div>
         </div>,
         document.body
       )}

       <div className="text-center mb-8">
         <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-green-500/10 text-green-400 border border-green-500/20 mb-4">
           <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
           <span className="text-sm font-medium">Generation Complete</span>
         </div>
         <h2 className="text-3xl font-bold text-white mb-2">Your Professional Headshot</h2>
         <p className="text-slate-400">Optimized for LinkedIn, Resume, and Corporate Profiles.</p>
       </div>

       {/* Watermark Notice for Free Users */}
       {!isPremium && (
          <div className="mb-6 p-3 bg-amber-500/10 border border-amber-500/20 rounded-xl flex items-center justify-center gap-2 text-amber-400 text-sm animate-fade-in">
             <div className="p-1 bg-amber-500/20 rounded-full"><Sparkles className="w-3 h-3" /></div>
             <span>Free Version: Watermark applied. Upgrade to PRO to remove it.</span>
          </div>
       )}

       {isUpscaled && (
          <div className="mb-6 p-3 bg-blue-500/10 border border-blue-500/20 rounded-xl flex items-center justify-center gap-2 text-blue-400 text-sm">
            <Sparkles className="w-4 h-4" />
            <span>Image upscaled to 2K High Resolution</span>
          </div>
       )}

       <div className="grid md:grid-cols-2 gap-8 items-center justify-center mb-8">
          {/* Before */}
          <div className="relative group rounded-2xl overflow-hidden border border-slate-700 bg-slate-800/50">
             <img src={originalImage} alt="Original" className="w-full h-auto object-cover opacity-60 grayscale transition-all duration-500 group-hover:grayscale-0 group-hover:opacity-100" />
             <div className="absolute top-4 left-4 bg-black/60 backdrop-blur px-3 py-1 rounded-lg text-xs font-bold text-white border border-white/10">
               BEFORE
             </div>
          </div>

          {/* After */}
          <div className="relative group rounded-2xl overflow-hidden shadow-2xl shadow-blue-500/20 border border-blue-500/30 ring-4 ring-blue-500/10 transition-all duration-300">
             {isUpscaling && (
               <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-[2px] z-20 flex flex-col items-center justify-center">
                  <Loader2 className="w-10 h-10 text-blue-400 animate-spin mb-3" />
                  <p className="text-white font-bold">Upscaling to 2K...</p>
               </div>
             )}

             {/* Image Composition Container */}
             <div className="relative w-full h-auto" style={getPreviewStyle()}>
               {/* Base Sharp Image Layer */}
               <img 
                  src={generatedImage.url} 
                  alt="Generated Headshot Base" 
                  className="w-full h-auto block"
               />

               {/* Watermark Overlay for Display (Visual CSS only) */}
               {!isPremium && (
                  <div className="absolute bottom-4 left-4 flex flex-col items-start pointer-events-none select-none z-20">
                     <p className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-blue-400 text-[1.2rem] md:text-[1.5rem] font-black drop-shadow-md leading-none mb-1">
                       KrishnaLense.AI
                     </p>
                     <p className="text-slate-400 text-[0.6rem] md:text-[0.7rem] font-bold drop-shadow-md uppercase tracking-widest">
                       By Dr. Krishna Karoo
                     </p>
                  </div>
               )}

               {/* Blurred Overlay Layer with Mask */}
               {blurAmount > 0 && (
                 <img 
                    src={generatedImage.url} 
                    alt="Generated Headshot Blur" 
                    className="absolute inset-0 w-full h-full object-cover pointer-events-none"
                    style={{ 
                      filter: `blur(${blurAmount}px)`,
                      maskImage: 'radial-gradient(circle at center, transparent 30%, black 80%)',
                      WebkitMaskImage: 'radial-gradient(circle at center, transparent 30%, black 80%)',
                    }}
                 />
               )}

               {/* Vignette Overlay */}
               {vignetteAmount > 0 && (
                 <div 
                   className="absolute inset-0 w-full h-full pointer-events-none"
                   style={{ 
                     background: `radial-gradient(circle, transparent 40%, rgba(0,0,0,${(vignetteAmount / 10) * 0.8}) 100%)` 
                   }}
                 />
               )}
             </div>
             
             <div className="absolute top-4 left-4 bg-blue-600 px-3 py-1 rounded-lg text-xs font-bold text-white shadow-lg z-10">
               AFTER
             </div>

             {!isUpscaled && !isUpscaling && (
                <button 
                  onClick={handleUpscaleClick}
                  className="absolute bottom-4 right-4 bg-slate-900/80 hover:bg-blue-600 backdrop-blur text-white px-3 py-2 rounded-lg text-sm font-bold flex items-center gap-2 transition-all border border-white/10 hover:border-blue-400 shadow-lg z-10"
                >
                  <Sparkles className="w-4 h-4 text-yellow-400" />
                  Upscale to 2K
                </button>
             )}
          </div>
       </div>

       {/* Controls Section */}
       <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-6 mb-10 backdrop-blur-sm">
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8 pb-8 border-b border-slate-700/50">
            {/* Basic Sliders */}
            <div className="space-y-6">
               <div className="flex items-center gap-2 text-slate-300 mb-4">
                  <SlidersHorizontal className="w-4 h-4 text-blue-400" />
                  <span className="text-sm font-bold uppercase tracking-wider">Basic Adjustments</span>
               </div>

                {/* Blur Slider */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-slate-400 flex items-center gap-2">
                      <Aperture className="w-3 h-3" /> Blur
                    </span>
                    <span className="text-xs font-mono text-slate-500">{blurAmount * 10}%</span>
                  </div>
                  <input 
                    type="range" min="0" max="10" step="1"
                    value={blurAmount}
                    onChange={(e) => setBlurAmount(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-blue-500"
                  />
                </div>

                {/* Vignette Slider */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-slate-400 flex items-center gap-2">
                      <Circle className="w-3 h-3" /> Vignette
                    </span>
                    <span className="text-xs font-mono text-slate-500">{vignetteAmount * 10}%</span>
                  </div>
                  <input 
                    type="range" min="0" max="10" step="1"
                    value={vignetteAmount}
                    onChange={(e) => setVignetteAmount(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-blue-500"
                  />
                </div>
            </div>

            {/* Advanced Sliders */}
            <div className="space-y-6">
               <div className="flex items-center gap-2 text-slate-300 mb-4">
                  <Activity className="w-4 h-4 text-purple-400" />
                  <span className="text-sm font-bold uppercase tracking-wider">Advanced Adjustments</span>
               </div>

                {/* Sharpness */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-slate-400 flex items-center gap-2">
                      <Activity className="w-3 h-3" /> Sharpness
                    </span>
                    <span className="text-xs font-mono text-slate-500">{sharpness}%</span>
                  </div>
                  <input 
                    type="range" min="0" max="100" step="1"
                    value={sharpness}
                    onChange={(e) => setSharpness(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-purple-500"
                  />
                </div>

                {/* Saturation */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-slate-400 flex items-center gap-2">
                      <Droplets className="w-3 h-3" /> Saturation
                    </span>
                    <span className="text-xs font-mono text-slate-500">{saturation}%</span>
                  </div>
                  <input 
                    type="range" min="0" max="200" step="10"
                    value={saturation}
                    onChange={(e) => setSaturation(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-purple-500"
                  />
                </div>

                {/* Contrast */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-slate-400 flex items-center gap-2">
                      <SunMedium className="w-3 h-3" /> Contrast
                    </span>
                    <span className="text-xs font-mono text-slate-500">{contrast}%</span>
                  </div>
                  <input 
                    type="range" min="0" max="200" step="10"
                    value={contrast}
                    onChange={(e) => setContrast(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-purple-500"
                  />
                </div>
            </div>
          </div>

          {/* Filter Selector */}
          <div>
            <div className="flex items-center gap-2 mb-4 text-slate-300">
              <Wand2 className="w-4 h-4 text-blue-400" />
              <span className="text-sm font-bold uppercase tracking-wider">Color Grade</span>
            </div>
            
            <div className="flex overflow-x-auto pb-4 gap-4 snap-x custom-scrollbar px-2">
              {FILTERS.map((filter) => (
                <button
                  key={filter.id}
                  onClick={() => setActiveFilter(filter)}
                  className={`group relative flex-shrink-0 flex flex-col items-center gap-2 transition-all duration-300 outline-none focus:outline-none snap-center ${
                    activeFilter.id === filter.id ? 'scale-105' : 'hover:scale-105 opacity-70 hover:opacity-100'
                  }`}
                >
                  <div className={`w-14 h-14 rounded-full overflow-hidden border-2 transition-all ${
                    activeFilter.id === filter.id ? 'border-blue-500 ring-2 ring-blue-500/30' : 'border-slate-600'
                  }`}>
                    <img 
                      src={generatedImage.url} 
                      alt={filter.name}
                      className="w-full h-full object-cover"
                      style={{ filter: filter.value }}
                    />
                  </div>
                  <span className={`text-xs font-medium transition-colors ${
                    activeFilter.id === filter.id ? 'text-blue-400' : 'text-slate-500 group-hover:text-slate-300'
                  }`}>
                    {filter.name}
                  </span>
                </button>
              ))}
            </div>
          </div>
       </div>

        {/* Share Section */}
        <div className="mb-8 bg-slate-800/30 border border-slate-700/50 rounded-2xl p-6 flex flex-col items-center">
          <div className="flex items-center gap-2 mb-4 text-slate-400">
             <MessageSquare className="w-4 h-4" />
             <p className="text-sm font-bold uppercase tracking-wider">Customize & Share</p>
          </div>
          
          <textarea
            value={shareText}
            onChange={(e) => setShareText(e.target.value)}
            className="w-full max-w-lg bg-slate-900/80 border border-slate-700 rounded-xl p-3 text-sm text-slate-200 placeholder-slate-600 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none resize-none mb-6 transition-all"
            rows={2}
            placeholder="Write your caption here..."
          />

          <div className="flex gap-4">
            <button 
              onClick={() => handleShare('twitter')}
              className="p-3 rounded-full bg-[#1DA1F2] text-white hover:bg-[#1DA1F2]/90 transition-all shadow-lg shadow-[#1DA1F2]/30 transform hover:-translate-y-1"
              title="Share on Twitter"
            >
              <Twitter className="w-5 h-5" />
            </button>
            <button 
              onClick={() => handleShare('linkedin')}
              className="p-3 rounded-full bg-[#0A66C2] text-white hover:bg-[#0A66C2]/90 transition-all shadow-lg shadow-[#0A66C2]/30 transform hover:-translate-y-1"
              title="Share on LinkedIn"
            >
              <Linkedin className="w-5 h-5" />
            </button>
            <button 
              onClick={() => handleShare('facebook')}
              className="p-3 rounded-full bg-[#1877F2] text-white hover:bg-[#1877F2]/90 transition-all shadow-lg shadow-[#1877F2]/30 transform hover:-translate-y-1"
              title="Share on Facebook"
            >
              <Facebook className="w-5 h-5" />
            </button>
            <button 
              onClick={() => handleShare('instagram')}
              className="p-3 rounded-full bg-gradient-to-r from-pink-500 via-purple-500 to-orange-500 text-white hover:opacity-90 transition-all shadow-lg shadow-pink-500/30 transform hover:-translate-y-1"
              title="Share on Instagram"
            >
              <Instagram className="w-5 h-5" />
            </button>
          </div>
        </div>

       {/* Actions Section */}
       <div className="flex flex-col gap-6">
         
         <button 
             onClick={handleDownload}
             disabled={isDownloading || isUpscaling}
             className="w-full flex items-center justify-center gap-3 px-8 py-5 bg-white text-slate-900 rounded-2xl font-bold text-lg hover:bg-slate-200 transition-colors shadow-xl hover:shadow-white/10 disabled:opacity-50 disabled:cursor-not-allowed"
           >
             {isDownloading ? (
               <Loader2 className="w-6 h-6 animate-spin" />
             ) : (
               <Download className="w-6 h-6" />
             )}
             {isDownloading ? 'Processing...' : 'Download High-Res Headshot'}
         </button>

         {/* Passport Studio Section */}
         <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-6 relative overflow-hidden group">
            <div className="absolute inset-0 bg-gradient-to-r from-blue-600/10 to-purple-600/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            
            <div className="flex flex-col md:flex-row items-center justify-between gap-6 relative z-10">
              <div className="flex items-start gap-4">
                <div className="p-3 bg-blue-500/20 rounded-xl hidden sm:block">
                  <FileText className="w-8 h-8 text-blue-400" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    Passport Photo Studio
                    <span className="text-[10px] bg-blue-500 text-white px-2 py-0.5 rounded-full">NEW</span>
                  </h3>
                  <p className="text-slate-400 text-sm mb-2">Generate official document photos formatted for A4 printing.</p>
                  <div className="flex gap-3 text-xs text-slate-500 font-medium">
                    <span className="flex items-center gap-1"><Grid3X3 className="w-3 h-3" /> Multiple Layouts</span>
                    <span className="flex items-center gap-1"><Scissors className="w-3 h-3" /> Cut Guides</span>
                    <span className="flex items-center gap-1"><Printer className="w-3 h-3" /> Print Ready</span>
                  </div>
                </div>
              </div>

              <button 
                onClick={handlePassportSheet}
                disabled={isGeneratingPassport}
                className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-3 bg-slate-700 text-white rounded-xl font-bold border border-slate-600 hover:bg-blue-600 hover:border-blue-500 transition-colors disabled:opacity-50 shadow-lg whitespace-nowrap"
              >
                {isGeneratingPassport ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                    <Printer className="w-5 h-5" />
                )}
                Open Studio
              </button>
            </div>
         </div>
         
         <button 
           onClick={onReset}
           disabled={isUpscaling}
           className="w-full flex items-center justify-center gap-2 px-8 py-4 bg-transparent text-slate-400 rounded-xl font-medium hover:text-white hover:bg-slate-800 transition-colors disabled:opacity-50"
         >
           <RefreshCw className="w-5 h-5" />
           Try Another Style
         </button>
       </div>
    </div>
  );
};
